### ISSUE TITLE
Games of all sorts don't work 

### ISSUE THREAD

**Issue by PalanixYT** [djpohly/dwl#101]
When trying to use mouse as input for various games, you can only look down and every kind of mouse input gets interpreted as moving to the right. Games Include
Minecraft, Minecraft Bedrock Edition, CSGO i haven't tested any other games because i don't have any other ones

**Comment by PalanixYT** [comment]
If it matters at all, the mouse doesn't stay in the borders of the video game, meaning you move mouse to different monitor, even while aiming

**Comment by guidocella** [comment]
I think that needs the [pointer constraints patch](https://github.com/djpohly/dwl/compare/main...Bonicgamer:pointerconstraints0.patch)

**Comment by PalanixYT** [comment]
hmm, yes that results in the mouse input being registered correctly, however, you can still move the mouse of the game window, resulting in focus being lost and the game pausing
