### ISSUE TITLE
Crashes when pressing left and right mouse button simultaneously on window resize

### ISSUE THREAD

**Issue by notthewave** [djpohly/dwl#102]
I accidentally stumbled across this bug.

crashes with:
```
fault=ritty
```
this seems to happen no matter which application is resized.

**Comment by djpohly** [comment]
Specifically, it seems to happen if you are resizing, then press the "move" mouse button, then move the mouse.  "fault=ritty" is probably several overlapping lines of messages. Here's the
[full backtrace](https://github.com/djpohly/dwl/files/6231516/gdb.log) that I get.
