### ISSUE TITLE
Pipe status info to -s command for external bars

### ISSUE THREAD

**Issue by djpohly** [djpohly/dwl#103]
Looking for feedback from those who have been working on integrating with external bars...

The challenge in the current setup is that, unlike with X, the display server is not yet running when the compositor is launched, so you need a buffer between dwl and anything that wants to receive its info and display something graphical.  I think I've seen regular files used for the buffer, and it might be possible to use a named pipe if you juggle non-blocking and SIGPIPE just right.  I've managed to do it by setting up an anonymous pipe and giving the fd number to the startup command as an argument.  All of this feels hackish though.

If, instead, the status info were sent directly to standard input of the `-s` startup command, then that command could more easily forward it to the right place without the need to create an explicit buffer.  Would this potentially work better in the setups that you all have been experimenting with?

**Comment by novakne** [comment]
I'm for everything that can make it less hacky, removing the need to use a file would be a great start, it would be easier to make a default setup to share for everyone.
