### ISSUE TITLE
Crashes when last monitor is disconnected.

### ISSUE THREAD

**Issue by adigitoleo** [djpohly/dwl#107]
I use a NUC box quite a bit, and I the other day I noticed that when I disconnect the monitor (HMDI) the whole compositor exits/crashes. I'm running v0.2-2 on top of Arch, started from a tty.

Doesn't happen on weston, if that's of any help. Unfortunately I haven't had the chance to dig into the source all that much yet.

**Comment by Stivvo** [comment]
It is expected if that is the only monitor. However I'll see what can be done to fix this. All applications also remain open on weston after unplugging, right?

**Comment by adigitoleo** [comment]
Yeah with weston I can plug the monitor back in and it's (usually) fine. Not a big deal, it's just that I was switching monitors between a few machines recently and I noticed this.

Occasionally it seems to happen with multihead as well, if one of the monitors is powered off/disconnected (the first one? I need to check).

**Comment by Sevz17** [comment]
Fixed in 8cace1921823e250041f7d85d939960f33824451
