### ISSUE TITLE
Help with multi monitor setup

### ISSUE THREAD

**Issue by adigitoleo** [djpohly/dwl#110]
I haven't tried multihead setups before but I've now got two monitors and was looking to get dwl working.

By default (no configuration of the MonitorRules) the output is the same on both of them, and I can't control what is displayed independently (e.g. via the focusmon bindings). So I think some configuration is required here... has anyone run multihead dwl successfully? Any advice on how it is done would be helpful.

I also tried naming the two HDMI monitors in `config.h` ("HDMI-A-1" and "HDMI-A-2") but I get the same result. Basically I'm looking for a way to control workspaces on a per-monitor basis.

Cheers

**Comment by djpohly** [comment]
You have a couple of options to set your monitors' relative positions.  One is to edit `config.h` and set a different X/Y position for each monitor in the MonitorRules.  You can also use a tool like `wlr-randr` to configure this dynamically.

Another option - and one that I'm still considering making the default for unpatched dwl - is to change the `wlr_output_layout_add` call in dwl to `wlr_output_layout_add_auto` and let wlroots manage the monitors' positions.

**Comment by adigitoleo** [comment]
Cool, I was missing `wlr-randr` from my wayland list ;) I'll try again this weekend and see what I come up with.

<details><summary>I'm weird, but...</summary>
So far I've had a lot of fun running a super minimal Arch+dwl as my main OS for the last few months. I don't even miss the statusbar much except for occasionally checking the time :smile: I'll have to add a strftime to vim's statusline or something. Laptop is a different story, but I'll keep Xorg on there for now.</details>

**Comment by adigitoleo** [comment]
OK so `wlr-randr` is working fine for me now, `focusmon` bindings work and it looks like the workspaces are created on each monitor separately. I can drag floating windows to the other monitor as well which is nice. That's basically all I was looking for at the moment, so I'll close this and discussion of `wlr_output_layout_add_auto` can be continued in a relevant PR later.

Some info for anyone landing here in the future: `wlr-randr` is in the AUR at the moment (04/2021) and you'll need meson to build it. Here are some simple shell aliases that I'm using to manage my dual HDMI setup (run `wlr-randr` first to check your monitor names and change accordingly). I like to have HDMI-A-2 as my main monitor, and HDMI-A-1 is the (dynamic) second one, so:

```sh
alias mon,left='wlr-randr --output HDMI-A-2 --preferred --pos 0,0 --output HDMI-A-1 --preferred --pos -1920,0'
alias mon,right='wlr-randr --output HDMI-A-2 --preferred --pos 0,0 --output HDMI-A-1 --preferred --pos 1920,0'
```
Then I run either of those after plugging in the second monitor, depending on it's position relative to the first one (`wlr-randr` also seems smart enough to disable the second monitor when it is unplugged).

Thanks @djpohly for pointing me in the right direction.
