### ISSUE TITLE
Issues Starting DWL 

### ISSUE THREAD

**Issue by Preyt** [djpohly/dwl#113]
Whenever I try to start dwl , I am greeted with an error message:

> [backend/session/logind.c:189] Failed to activate session: Permission denied

I have to then start dwl has root. However when I do i get this error: ¨XDG_RUNTIME_DIR not set¨ . 

Why do i have to start dwl has root? and why is it stating that XDG_RUNTIME_DIR is not set when it actually is?

**Comment by dedguy21** [comment]
xdg-runtime set for root user? Doubtful

**Comment by Preyt** [comment]
I figured out the issue. It had nothing to do with dwl but it was a Systemd issue.  I discovered this issue here [https://github.com/systemd/systemd/pull/15111](url)

Since Sway solved this issue,  I installed sway , made a copy of the Polkit rules sway used and then uninstalled sway again. I then installed polkit and made use of the Polkit rules I got from sway. DWL now starts with no problem or issues.
