### ISSUE TITLE
Won't compile on Fedora 34

### ISSUE THREAD

**Issue by yurihentai** [djpohly/dwl#117]
wlroots 0.13 is installed:

    $ rpm -q wlroots
    wlroots-0.13.0-1.fc34.x86_64

and on both dwl 0.2.1 and latest git, running `make` yields this error

    server-header \
	    /stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
    make: server-header: No such file or directory
    make: *** [Makefile:29: xdg-shell-protocol.h] Error 127

Am I missing binaries? before `server-header` is `$WAYLAND_SCANNER` which uses `shell` and `pkg-config`, but I'm not sure which packages these binaries come from.

**Comment by djpohly** [comment]
It's looking for the `wayland-scanner` utility. In the spirit of teaching a person to fish:

* [pkgs.org](https://pkgs.org/search/?q=wayland-scanner&on=files)
* [rpmfind.net](https://rpmfind.net/linux/rpm2html/search.php?query=wayland-scanner&system=fedora)
* `yum whatprovides wayland-scanner`
* or generally on Fedora, they put the files needed to build software in a `-devel` version of the package

Choose your favorite. 😊

**Comment by yurihentai** [comment]
> It's looking for the `wayland-scanner` utility. In the spirit of teaching a person to fish:
> 
>     * [pkgs.org](https://pkgs.org/search/?q=wayland-scanner&on=files)
> 
>     * [rpmfind.net](https://rpmfind.net/linux/rpm2html/search.php?query=wayland-scanner&system=fedora)
> 
>     * `yum whatprovides wayland-scanner`
> 
>     * or generally on Fedora, they put the files needed to build software in a `-devel` version of the package
> 
> 
> Choose your favorite.

Probably the most helpful reply I've ever received from any open source developer. 

After running `yum whatprovides wayland-scanner`, I installed `wayland-devel`. Yesterday I thought it'd be in `wayland-protocols-devel`. Another `make`, and `make: cc: No such file or directory`. In the spirit of learning to fish, I ran `yum whatprovides cc`, returning `gcc` of course. Another `make`, returning `dwl.c:13:10: fatal error: libinput.h: No such file or directory`.

Running `yum whatprovides libinput` provides `libinput` which was already installed, so I appended `-devel` and got the right C libraries for compilation. For `libudev`, the `systemd-devel` package provides it. Lastly, `wlroots-devel` is needed instead of `wlroots` on Fedora, as well.

After all this, it compiles without error. Thank you!!!

**Comment by djpohly** [comment]
That's what happens when your dev's day job is teaching computer science. :)  Nice fishing.

There's probably a set of packages you'll want to install for compiling code (guessing you haven't done that before since you needed to install gcc).  On Arch you do `pacman -S base-devel`, on Debian derivatives it's `apt-get install build-essential`, and on RPM/yum systems it appears the command is
```
$ yum groupinstall “Development Tools”
```

**Comment by ma-choo** [comment]
I'm getting this error when trying to run make install on Fedora 34:

`cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/valgrind -I/usr/include/pixman-1 -I/usr/include/uuid        -c -o dwl.o dwl.c`
`dwl.c:40:10: fatal error: wlr/types/wlr_xdg_activation_v1.h: No such file or directory`
`   40 | #include <wlr/types/wlr_xdg_activation_v1.h>`
`      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`compilation terminated.`
`make: *** [<builtin>: dwl.o] Error 1`

I've installed wlroots-devel, wayland-protocols-devel, Development Tools and Development Libraries. I also ran a `yum whatprovides wlr/types/wlr_xdg_activation_v1.h`, but it returns nothing. How do I resolve this missing dependency?

**Comment by just-carlod** [comment]
I've got the same error as @ma-choo on ubuntu 21.04. I think the problem is too old version of wlroots in ubuntu repos (which is 0.12 for hirsute).

**Comment by nonetrix** [comment]
Same here also tried using a build I compiled on Arch but it couldn't find a .so file
