### ISSUE TITLE
Implement input-inhibitor protocol (support screen lockers)

### ISSUE THREAD

**Issue by adigitoleo** [djpohly/dwl#123]
We now have [swaylock](https://github.com/swaywm/swaylock) and [waylock](https://github.com/ifreund/waylock) for screen locking in wayland. I thought it would be worth opening an issue to track support for these. At the moment, I'm hopping to a new tty and using `vlock`, but I don't really know what the security implications are.

Note that I never used dwm so I don't know if this should be part of dwl at all, just putting it out there.

It seems that the input inhibitor protocol needs to be implemented? Or is that a job for wlroots? I'm still figuring out the wayland stack...

```
2021-05-26 16:42:39 - [swaylock-1.5/main.c:1186] Compositor does not support the input inhibitor protocol, refusing to run insecurely
```

**Comment by djpohly** [comment]
Yep, that's the protocol, and yes, let's add it as simply as possible. In this case, I believe wlroots leaves at least some portion of the implementation up to individual compositors.
