### ISSUE TITLE
Steam menus drawn in wrong position

### ISSUE THREAD

**Issue by TRPB** [djpohly/dwl#125]
When running Steam, the application works but when it starts up it's not drawn as a full tile until the tiles are rearranged somehow (e.g. adding a new tile). This isn't really a problem on its own since it's very easily fixed.

However, the menus seem drawn arbitrarily. In the state mentioned above, I have steam running on display 1 and the drop down menus (store, community, etc) appear on display 2. Once the tiles have been rearranged and it's drawn correctly, Steam's menus are drawn about 300px left of where they should be.

**Comment by adigitoleo** [comment]
I've seen this happen in various GUI programs as well, I haven't tracked it down properly yet but I think I remember it happening more (only?) when the GUI is running under XWayland. Do you know if Steam runs natively on wayland, or does it use XWayland? You can check using `xprop` (click on the window, if it prints something, then it's XWayland).

**Comment by pm4rcin** [comment]
@adigitoleo Steam of course runs on Xwaylad.

**Comment by Sevz17** [comment]
@TRPB, is this still happening?

**Comment by pm4rcin** [comment]
@Sevz17 I think I have the same problem. I have no external monitors. When I play e.g. Portal 2 while steam window is open on another tag when I click in game it registers clicks in steam and not in game. Another example when I have freetube (XWayland like steam) open on e.g. tag 2 mouse clicks keepassxc menus on another tab. It's reproducible every time.

**Comment by HadetTheUndying** [comment]
This is because Steam menus spawn a fresh Window(XWayland windows) for every menu and submenu some ungodly reason.

**Comment by Sevz17** [comment]
> @Sevz17 I think I have the same problem. I have no external monitors. When I play e.g. Portal 2 while steam window is open on another tag when I click in game it registers clicks in steam and not in game. Another example when I have freetube (XWayland like steam) open on e.g. tag 2 mouse clicks keepassxc menus on another tab. It's reproducible every time.

I think that's a different bug

**Comment by pm4rcin** [comment]
@Sevz17 yeah probably yes. How could I debug it or do you have any idea what could be the cause?

**Comment by Sevz17** [comment]
@pm4rcin, maybe related: Yesterday I realized I can't click in the settings window of VirtualBox if it is overlapping its parent.
Although I recommend open another issue for this.

**Comment by Sevz17** [comment]
Can anyone tell me if #218 fixes this issue?

**Comment by fauxmight** [comment]
There are  two separate issues being discussed in this thread. I don't have the initial issue that @TRPB mentions and cannot answer whether #218 resolves it.

However, I do have the issue reported by @pm4rcin: When Steam spawns a window, clicks to the child window are received by the main Steam window (underneath) and ignored by the child window (on top). I don't have this issue in any Xwayland application other than Steam. #223 resolves this matter perfectly for me.

**Comment by pm4rcin** [comment]
I've had the problem that without changing layout Steam friends menu was rendered on half a screen while the borders showed like it's on whole screen. Now with #218 when I open friends chat it is rendered on whole screen. I can't test multi monitor since Nvidia... I use AMD CPU for display and Nvidia for things like games but when I plug the external screen it's wlr-randr doesn't show it.
