### ISSUE TITLE
Compile error on void musl

### ISSUE THREAD

**Issue by oaspiazu** [djpohly/dwl#126]
Hello

It does not seem to compile on void musl despite of having both dependencies installed.
Thanks.

`$ doas xbps-install -S wlroots wayland-protocols
Password:
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
Package `wlroots' already installed.
Package `wayland-protocols' already installed.
$ make
Package wayland-scanner was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-scanner.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-scanner' found
server-header \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
make: server-header: No such file or directory
make: *** [Makefile:29: xdg-shell-protocol.h] Error 127`

**Comment by djpohly** [comment]
See #117.  If you want to do development on a distro that has separate -devel packages, you need to install those.

**Comment by oaspiazu** [comment]
Thanks!!
It is working now. 
On void you need 2 extra packages (+ dependencies) : wayland-devel and wlroots-devel.
