### ISSUE TITLE
Cursor cannot be captured by windows

### ISSUE THREAD

**Issue by nph278** [djpohly/dwl#128]
I just installed dwl on my linux installation, and noticed that when playing games that use the cursor for movement (Minecraft), they could not capture the cursor and the movement was messed up. The cursor would move the view, but it would stop when it hit the edge of the screen, and the cursor was visible the entire time.

**Comment by guidocella** [comment]
Apply the [pointer constraints patch](https://github.com/djpohly/dwl/compare/main...Bonicgamer:pointerconstraints0.patch)

**Comment by nph278** [comment]
When using that patch I get these compile-time errors:

```
dwl.c:929:13: error: implicit declaration of function ‘WLR_SURFACE’ [-Werror=implicit-function-declaration]
  929 |         if (WLR_SURFACE(selclient()) == constraint->surface) {
      |             ^~~~~~~~~~~
dwl.c:929:38: error: comparison between pointer and integer [-Werror]
  929 |         if (WLR_SURFACE(selclient()) == constraint->surface) {
      |                                      ^~
```

**Comment by Sevz17** [comment]
Use `client_surface(selclient())` instead of `WLR_SURFACE(selclient())`

**Comment by nph278** [comment]
> Use `client_surface(selclient())` instead of `WLR_SURFACE(selclient())`

Thanks! This worked, should the patch be updated?

**Comment by Sevz17** [comment]
Yes
