### ISSUE TITLE
Cannot drag selected objects like I can in Sway or X

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [djpohly/dwl#134]
I'm not sure if this is a bug or a feature request. I can't drag objects, such as links, text, or images with my mouse. Programs that expect this functionality include Ungoogled Chromium, LibreWolf, and various electron-based apps.

I can select these items just fine, but I can't move them around.

**Comment by PalanixYT** [comment]
It's not currently implemented in dwl yet.

**Comment by Sevz17** [comment]
Fixed in 330792b1fc37db86743d7c186577776e05295e00
