### ISSUE TITLE
Not registering input

### ISSUE THREAD

**Issue by KSPAtlas** [djpohly/dwl#140]
I am using this Wayland compositor on Gentoo Linux. However, the WM itself does not register any input, only the programs that run on it. So foot receives my keystrokes, but not DWL

**Comment by Sevz17** [comment]
Are you in the input group? If not, you can run as root `gpasswd -a <user> input`

**Comment by mikejzx** [comment]
> I am using this Wayland compositor on Gentoo Linux. However, the WM itself does not register any input, only the programs that run on it. So foot receives my keystrokes, but not DWL

@KSPAtlas I also ran into a similar issue on Gentoo (my config changes appeared to not be doing anything so the WM seemed non-functional).  If you're using DWL from the GURU overlay, ensure that you have the `savedconfig` USE flag enabled, or else any changes you make to the `/etc/portage/savedconfig/gui-wm/dwl-...` file won't have any effect.

**Comment by PalanixYT** [comment]
this sounds like either the wrong keymap is used and the keybinds are not correct or the config didn't save and the wrong modkey is active.
@sevz17 this has been stale for more than 2 years. Close?
