### ISSUE TITLE
Better Touchpad Support

### ISSUE THREAD

**Issue by shadow5013** [djpohly/dwl#141]
A lot of features (e.g. disable while typing,  acceleration, middle click emulation, tap and drag ) are missing. It would be nice to have them.

**Comment by xi** [comment]
Can you give more context? As far as I understand, most of this can already be achieved by patching `createpointer()`. See also the [libinput docs on configuration](https://wayland.freedesktop.org/libinput/doc/latest/configuration.html). If by "tab and drag" you mean drag and drop see #134 and #144.

Does this answer your question or is there something missing?

**Comment by shadow5013** [comment]
I kinda expected to configure touchpad from the `config.h` much like keyboard.

**Comment by pm4rcin** [comment]
@dimkr as mentioned [here](https://github.com/djpohly/dwl/pull/229#issuecomment-1129107612) we want it to be setup by config.h so if you could rework your PR it'd be great.

**Comment by dimkr** [comment]
> @dimkr as mentioned https://github.com/djpohly/dwl/pull/229#issuecomment-1129107612 we want it to be setup by config.h so if you could rework your PR it'd be great.

My use case is different: I want to be able to change these settings without recompiling, because it's a binary used by multiple users (some are left-handed, etc').
