### ISSUE TITLE
Can't compile on EndeavourOS

### ISSUE THREAD

**Issue by pm4rcin** [djpohly/dwl#142]
Hi, I tried to compile dwl on Endeavouros by cloning and executing make and uncommenting XWAYLAND support. I installed https://aur.archlinux.org/packages/wlroots-eglstreams-git/ and xwayland and wayland-protocols. I have nvidia GPU with proprietary driver 470.63.01 and here's [log](https://gist.github.com/pm4rcin/a67103224c3e409aeb6c0e1bbe82059d).

**Comment by PalanixYT** [comment]
main branch of dwl isn't build againt the git version of wlroots

**Comment by pm4rcin** [comment]
The real problem is that dwl is currently built against wlroots 0.14 while the newest version of wlroots is 0.14.1 from July 8th [see](https://github.com/swaywm/wlroots/releases/latest).

**Comment by PalanixYT** [comment]
no, the missing function is still in 0.14.1

**Comment by pm4rcin** [comment]
I did git checkout but the same error appeared since wlroots-next branch doesn't have new function.

**Comment by pm4rcin** [comment]
Since it was merged to wlroots-next I'll close issue.
