### ISSUE TITLE
setting mode via wlr-randr causes screen artifact

### ISSUE THREAD

**Issue by tleydxdy** [djpohly/dwl#147]
It leaves large parts of the screen flash checker board pattern, and makes dwl have high cpu usage. the checker board remains even after setting back to the original mode.

Also it seems like the handling of output changing is problematic, dwl would crash when I turn off the monitor or switch it from freesync on to off for example (I was trying to debug the above problem)

I patched my dwl to set the mode I want at the launch and the artifact is not there if done that way

**Comment by PalanixYT** [comment]
The artifacts are caused by the pageflip fix. One solution would be to use the monitor-config patch

**Comment by sevz17** [comment]
@tleydxdy, #287 should fix this, can you test it please?

**Comment by tleydxdy** [comment]
@sevz17 can confirm that changing resolution works, but now when i run main setting resolution actually crashes, rather than the artifact before :(
