### ISSUE TITLE
Question: HiDPI

### ISSUE THREAD

**Issue by elleven11** [djpohly/dwl#15]
So a reason i want to try out wayland (with dwm ofcourse), is because of a problem that i have with X11. Simply, i cannot adjust different dpi values for different monitors (i have a 4k 35" monitor and a 1080p 24" monitor), which makes using dwm with X11 almost impossible on my other montior. I've heard that with wayland this is not the case, you can change the dpi values for different monitors. is this true? if so, how do i do it? i cannot find any resource online about it, i've just heard it on the gentoo forums.

**Comment by djpohly** [comment]
Check out config.h.  One of the fields in `MonitorRule` is called `scale` - simply make a rule with your monitor's Wayland name (like "HDMI-A-1") and the scale field set to a factor to scale windows by when they are on that monitor.  When you move a window from one monitor to another, dwl (actually, wlroots) will tell it to rescale.

**Comment by debeetle** [comment]
Fortunately I find this way to adjust dpi for hidpi monitor. But it ends up with the scale rate which makes my mouse cursor looks too big. What can I do for fixing that? I'm appreciate for any advisor.

**Comment by sevz17** [comment]
In this [line](https://github.com/djpohly/dwl/blob/main/dwl.c#L2176) change the `24` to a lower number, alternatively you can apply this [patch](https://github.com/djpohly/dwl/wiki/cursortheme) that makes easier change that value
