### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by tailornirav** [djpohly/dwl#156]
I cloned the current dwl master branch and did the make command. Here is the output.
`cp config.def.h config.h`
`/usr/bin/wayland-scanner server-header \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h`
`/usr/bin/wayland-scanner server-header \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.h`
`/usr/bin/wayland-scanner server-header \
	protocols/idle.xml idle-protocol.h`
`/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c`
`/usr/bin/wayland-scanner private-code \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.c`
`/usr/bin/wayland-scanner private-code \
	protocols/idle.xml idle-protocol.c`
`cc -march=native -O3 -pipe -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/elogind       -c -o dwl.o dwl.c`
`cc -march=native -O3 -pipe -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/elogind       -c -o xdg-shell-protocol.o xdg-shell-protocol.c`
`cc -march=native -O3 -pipe -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/elogind       -c -o wlr-layer-shell-unstable-v1-protocol.o wlr-layer-shell-unstable-v1-protocol.c`
`cc -march=native -O3 -pipe -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/elogind       -c -o idle-protocol.o idle-protocol.c`
`dwl.c: In function ‘arrangelayer’:`
`dwl.c:554:25: warning: implicit declaration of function ‘wlr_layer_surface_v1_close’; did you mean wlr_layer_surface_v1_destroy’? [-Wimplicit-function-declaration]`
`  554 |                         wlr_layer_surface_v1_close(wlr_layer_surface);`
`      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~`
`      |                         wlr_layer_surface_v1_destroy`
`dwl.c: In function ‘createlayersurface’:`
`dwl.c:929:52: error: ‘struct wlr_layer_surface_v1’ has no member named ‘client_pending’`
`  929 |         wl_list_insert(&m->layers[wlr_layer_surface->client_pending.layer],`
`      |                                                    ^~`
`dwl.c:935:55: error: ‘struct wlr_layer_surface_v1’ has no member named ‘client_pending’`
`  935 |         wlr_layer_surface->current = wlr_layer_surface->client_pending;`
`      |                                                       ^~`
`make: *** [<builtin>: dwl.o] Error 1`

This is my Wayland protocol version. I built it from it's git master repository as well.
`00:19> wayland-scanner --version`
`wayland-scanner 1.19.0`

**Comment by Sevz17** [comment]
You are using wlroots-git, use [wlroots-next](https://github.com/djpohly/dwl/tree/wlroots-next) branch or use wlroots-0.14.*
