### ISSUE TITLE
dwl segfault when run something depend on libSDL2

### ISSUE THREAD

**Issue by halo-shit** [djpohly/dwl#170]
such like: SDL_VIDEODRIVER=wayland ffplay something.mp4

**Comment by raphaelr** [comment]
I've attached a patch which fixes it on the native drm backend.

On virtual backends (x11/wl) ffplay crashes because SDL2 doesn't seem to be able to handle a wl_output.mode event with refresh = 0 (which the spec explicitly allows). I'll have to look into THAT one further.

**Comment by halo-shit** [comment]
> I've attached a patch which fixes it on the native drm backend.
> 
> On virtual backends (x11/wl) ffplay crashes because SDL2 doesn't seem to be able to handle a wl_output.mode event with refresh = 0 (which the spec explicitly allows). I'll have to look into THAT one further. (update: fixed upstream [libsdl-org/SDL#4785](https://github.com/libsdl-org/SDL/issues/4785))

Thanks for your hard work. BTW I am using the latest version of libSDL2 which merge the patch. But still got segfault. dwl crashed and nothing like debug info I can get from the tty terminal. I don't know how to help you to fix the bug😂

**Comment by halo-shit** [comment]
debug coredump wtih gdb:

⋊> ~ coredumpctl debug                                                                                                                                                   01:51:13
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
           PID: 58316 (dwl)
           UID: 2513 (trinity)
           GID: 999 (trinity)
        Signal: 11 (SEGV)
     Timestamp: Sun 2021-11-14 01:51:06 HKT (9s ago)
  Command Line: ./dwl/dwl
    Executable: /trinity/dwl/dwl
 Control Group: /user.slice/user-2513.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-2513.slice
       Session: 1
     Owner UID: 2513 (trinity)
       Boot ID: 27ae63731868483f8ef6972b39486e0d
    Machine ID: 70afea0a90f0bf32df71ee3d60dd1082
      Hostname: none
       Storage: journal
       Message: Process 58316 (dwl) of user 2513 dumped core.

GNU gdb (Gentoo 11.1 vanilla) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /trinity/dwl/dwl...

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:gdk-wayland (deleted) during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file /memfd:xwayland-shared (deleted) during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing

warning: Can't open file anon_inode:i915.gem which was expanded to anon_inode:i915.gem during file-backed mapping note processing
[New LWP 58316]
[New LWP 58317]
[New LWP 58318]
[New LWP 58320]
[New LWP 58319]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./dwl/dwl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  setfullscreen (c=0x55f4343a71a0, fullscreen=1) at dwl.c:1032
1032			resize(c, c->mon->m.x, c->mon->m.y, c->mon->m.width, c->mon->m.height, 0);
[Current thread is 1 (Thread 0x7fdbb913e940 (LWP 58316))]
(gdb)

**Comment by raphaelr** [comment]
Have you applied https://patch-diff.githubusercontent.com/raw/djpohly/dwl/pull/171.patch ?

This exact crash is what this patch is supposed to fix. If yes I'm out of ideas since I can't reproduce it

**Comment by halo-shit** [comment]
> Have you applied https://patch-diff.githubusercontent.com/raw/djpohly/dwl/pull/171.patch ?
> 
> This exact crash is what this patch is supposed to fix. If yes I'm out of ideas since I can't reproduce it

fixed. dwl doesn't crash anymore and ffplay works. Sadly, dota2 got another segfault.

**Comment by halo-shit** [comment]
thank you very much
