### ISSUE TITLE
Make fails <wlr/render/allocator.h>

### ISSUE THREAD

**Issue by Moempfred** [djpohly/dwl#174]
I am on a fresh Arch install. wlroots and wayland-protocols is installed.

`
dwl.c:16:10: fatal error: wlr/render/allocator.h: No such file or directory      
      16 | #include <wlr/render/allocator.h>  
           |  
compilation terminated
`

**Comment by raphaelr** [comment]
Which dwl/wlroots versions are you using? The newly released dwl 0.2.2 depends on wlroots 0.15, which isn't in the arch repos as of now.

**Comment by Moempfred** [comment]
It is version 0.14.1-2. So I guess I'll have to use the Git version of wlroots for now!? I think issue can be closed

**Comment by Moempfred** [comment]
Ok, I am stuck. I've installed the git-version of wlroots. Make fails at pixman.h (which is installed)
