### ISSUE TITLE
Hidden status bar

### ISSUE THREAD

**Issue by rustzz** [djpohly/dwl#195]
Status bar not shows, why?
OS on screen
![20220219_22h43m20s_grim](https://user-images.githubusercontent.com/74064444/154812573-22810ee0-5ead-4327-8370-30351bd1d541.png)

**Comment by PalanixYT** [comment]
Because there isn't a status bar. 

dwl has opted for a modular approach, some good bars are: somebar(looks exactly like dwmbar),
waybar(most customization options),  or dtao(dzen clone)

I would recommend somebar, it's the easiest to use. waybar and dtao need a script to work.

**Comment by rustzz** [comment]
ok, thx)

**Comment by ahmadraniri1994** [comment]
`Providing a built-in status bar is an exception to this goal`

The README stated.
