### ISSUE TITLE
[Question] gaps patch is outdated.

### ISSUE THREAD

**Issue by ahmadraniri1994** [djpohly/dwl#197]
I try this [gaps patch](https://github.com/djpohly/dwl/compare/main...Bonicgamer:vanitygaps.patch) , it doesn't work with dwl latest master.

**Comment by Sevz17** [comment]
It's already updated

**Comment by ahmadraniri1994** [comment]
> It's already updated

Really ?
I try to patch with this command :
`patch -p1 < path/to/patch.diff`

but doesn't work. How do you apply patch BTW ?

**Comment by Sevz17** [comment]
Try download it again

**Comment by Sevz17** [comment]
I rebased it against main today.

**Comment by ahmadraniri1994** [comment]
What download, patch or the DWL source ?
how do you apply the patch ?

**Comment by ahmadraniri1994** [comment]
OK, try it later thanks.
