### ISSUE TITLE
XDG_RUNTIME_DIR must be set

### ISSUE THREAD

**Issue by lytanz** [djpohly/dwl#199]
I do follow as the following operation
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
dwl
But there still exists the error:
XDG_RUNTIME_DIR must be set
OS is Archlinux

**Comment by Sevz17** [comment]
I can't reproduce, what is the output of `env | grep XDG_RUNTIME_DIR` before launching dwl?

**Comment by lytanz** [comment]
Is there a tutorial for that how to use dwl？
I use the dwl on the archlinux which is simulated by vmware.
I can run sway but it can not display the picture.just a black screen.
when I logined as root ,the errors disappeared，but all got into black.

**Comment by lytanz** [comment]
> 
env | grep
the output:
 XDG_RUNTIME_DIR=/tmp/xdg-runtime-1000

**Comment by Sevz17** [comment]
> Is there a tutorial for that how to use dwl?

Nop, just the readme and reading `config.def.h` for default config.

> I can run sway but it can not display the picture.just a black screen.
when I logined as root ,the errors disappeared，but all got into black.

Are you in the input and video groups?
if not:
```sh
sudo usermod -aG video,input $USER
```

**Comment by lytanz** [comment]
yes,I do，but it doesn’t seem to work anyway.
I am going to quit trying the  dwl because I cannot solve this problem

**Comment by lytanz** [comment]
> I do follow as the following operation
> export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
> mkdir -p $XDG_RUNTIME_DIR
> dwl
> But there still exists the error:
> XDG_RUNTIME_DIR must be set
> OS is Archlinux

Do I need to write this to /etc/profile

**Comment by lytanz** [comment]
> > Is there a tutorial for that how to use dwl?
> 
> Nop, just the readme and reading `config.def.h` for default config.
> 
> > I can run sway but it can not display the picture.just a black screen.
> > when I logined as root ,the errors disappeared，but all got into black.
> 
> Are you in the input and video groups? if not:
> 
> ```shell
> sudo usermod -aG video,input $USER
> ```

![image](https://user-images.githubusercontent.com/86844588/158137533-70f4c52a-4390-4558-90be-894a82eb6986.jpg)

**Comment by lytanz** [comment]
> > Is there a tutorial for that how to use dwl?
> 
> Nop, just the readme and reading `config.def.h` for default config.
> 
> > I can run sway but it can not display the picture.just a black screen.
> > when I logined as root ,the errors disappeared，but all got into black.
> 
> Are you in the input and video groups? if not:
> 
> ```shell
> sudo usermod -aG video,input $USER
> ```

Can you show me the whole installation steps of dwl on vmware ，my bro
I just have configured the basic system

**Comment by Sevz17** [comment]
> Do I need to write this to /etc/profile

No

**Comment by Sevz17** [comment]
> when I press the enter， it displays nothing，just a black screen

black?, hmm, it should a gray screen

**Comment by lytanz** [comment]
> > when I press the enter， it displays nothing，just a black screen
> 
> black?, hmm, it should a gray screen
oh ，just the light problem

**Comment by Sevz17** [comment]
> Can you show me the whole installation steps of dwl on vmware ，my bro I just have configured the basic system

Well, I don't know how to use vmware, but as far I see, you are running it as the root user, try running it as another user

**Comment by lytanz** [comment]
> > Can you show me the whole installation steps of dwl on vmware ，my bro I just have configured the basic system
> 
> Well, I don't know how to use vmware, but as far I see, you are running it as the root user, try running it as another user

when I run sway，it shows

Arch Linux 5.16.14-arch1-1 (tty1)
Arch login: arch
Password:
Last login: Mon Mar 14 22:57:15 on ttyl
Arch, set Stern alacritty
Arche. sway -d ›sway. log
00:00:00,000 (sway/main.c:343] Suay version 1.7
00:00:00.000 (sway/main.c:344] ulroots version 0.15.0
00:00:00.007 [sway/main.c:120] Linux Arch 5.16.14-arch1-1 #1 SMP PREEMPT Eri, 11 Mar 2022 17:10:36 +0000 x86_64 GNU/DINO
00:00:00.007 (sway/main.c:136] Contents of /etc/os-release:
00:00:00.007 [sway/nain.c:120] MAME-"Arch Linux"
00:00:00.007 (sway/main.c:120] PRETTY MAME-"Arch Linux"
00:00:00.007 [sway/nain.c:120] ID=arch
00:00:00,008 [sway/nain.c:120] BUILD_ID-rolling
00:00:00.008 (sway/nain.c:120] ANSI COLOR="38:2:23:147:209*
00:00:00.008 (sway/nain.c:120] HOME_URL="https://archlinux.org/'
00:00:00.008 [sway/nain.c:120] DOCUMENTATION _URL="https:/wiki.archlinux.org/
00:00:00.008 (sway/nain.c:120] SUPPORT_URL-"https://bbs.archlinux.org."
00:00:00.008 [suay/main.c:120] BUG _REPORT_URL="https://bugs.archlinux.org."
00:00:00.008 (suau/nain.c:120] LOGO=archl inux-logo
00:00:00.008 [suay/main.c:108] LD LIBRARY_PATH=
00:00:00.008 (sway/main.c:108] LD_PRELOAD=
00:00:00.008 (sway/nan.c:108] PATH=usr/local/sbin:
/usp/bin/vendor_per:/uspbey.con
00:00:00,008 (sway/main.c: 108] SUAYSOCK-
00:00:00.006 (sway/server.c:501 Preparing Wayland server
initialization
00:00:00.009 (ulr] (libseat] (libseat/backend/seatd.c:B0] Could not connect to socket /run/seatd,sock: Mo such file or directony

**Comment by lytanz** [comment]
I find some errors，I attempt to solve those.

**Comment by lytanz** [comment]
> Try exporting `LIBSEAT_BACKEND=logind` before launching it

![image](https://user-images.githubusercontent.com/86844588/158207128-46bb3df8-bf05-474e-91b0-1237eeed9243.jpg)

now I can login into the interface，but I cannot call out the terminal

**Comment by Sevz17** [comment]
> > Try exporting `LIBSEAT_BACKEND=logind` before launching it
> 
> whatever i input is invalid，

Ok, you aren't running it as root, are you?

**Comment by lytanz** [comment]
> > > Try exporting `LIBSEAT_BACKEND=logind` before launching it
> > 
> > 
> > whatever i input is invalid，
> 
> Ok, you aren't running it as root, are you?

just common user

**Comment by Sevz17** [comment]
> > I can run sway but it can not display the picture.just a black screen.
> > when I logined as root ,the errors disappeared，but all got into black.
> 
> Are you in the input and video groups? if not:
> 
> ```shell
> sudo usermod -aG video,input $USER
> ```

maybe your user is not in the input group, so Sway cannot detect your keys

**Comment by lytanz** [comment]
> > > I can run sway but it can not display the picture.just a black screen.
> > > when I logined as root ,the errors disappeared，but all got into black.
> > 
> > 
> > Are you in the input and video groups? if not:
> > ```shell
> > sudo usermod -aG video,input $USER
> > ```
> 
> maybe your user is not in the input group, so Sway cannot detect your keys

yes the user in these groups

**Comment by Sevz17** [comment]
ok, try the same in dwl, the default keybinding for opening alacritty is `alt+shift+return`

**Comment by lytanz** [comment]
Ok，I will send it to you later

**Comment by fauxmight** [comment]
@lytanz If you are still unable to start a terminal in dwl, are you able to start a terminal from Sway?
You may have to install foot, the default terminal for Sway, to test this. `pacman -S foot`
The default binding in Sway to start a terminal is `Window Key + Enter`

If this works in Sway but not in dwl, we can begin to rule out an input issue with wlroots inside your virtual machine and focus on dwl.

**Comment by lytanz** [comment]
> @lytanz If you are still unable to start a terminal in dwl, are you able to start a terminal from Sway? You may have to install foot, the default terminal for Sway, to test this. `pacman -S foot` The default binding in Sway to start a terminal is `Window Key + Enter`
> 
> If this works in Sway but not in dwl, we can begin to rule out an input issue with wlroots inside your virtual machine and focus on dwl.

I think this problem just exists in virtual machine.I have seaeched one page which tacked about this problem，but I still cannot find the effective method.

**Comment by djpohly** [comment]
This appears to have gotten pretty far from "XDG_RUNTIME_DIR must be set", and it's not clear that we're dealing with a dwl bug here.  @lytanz - would you be able to take the support conversation to Discord?

**Comment by lytanz** [comment]
> > ok, try the same in dwl, the default keybinding for opening alacritty is `alt+shift+return`
> 
> Hei bro， I find that this situation just exists in vmware. In my physical pc，it runs well

the dwl runs will on my physical machine.
My thought is that test it  inside the virtual machine ，if it runs well，I will install dwl in my pc

**Comment by djpohly** [comment]
Nothing to be sorry about. :slightly_smiling_face: Just wanted to redirect it to the right forum!

**Comment by lytanz** [comment]
> Nothing to be sorry about. 🙂 Just wanted to redirect it to the right forum!

I will always support you for your work！

**Comment by fauxmight** [comment]
@lytanz The "Discord" forum djpohly mentioned is [here](https://discord.gg/jJxZnrGPWN)

**Comment by lytanz** [comment]
> I do follow as the following operation
> export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
> mkdir -p $XDG_RUNTIME_DIR
> dwl
> But there still exists the error:
> XDG_RUNTIME_DIR must be set
> OS is Archlinux

when you run dwl，you can type this command which can work well

WLR_NO_HARDWARE_CURSORS=1 dwl

**Comment by lytanz** [comment]
> > Is there a tutorial for that how to use dwl?
> 
> Nop, just the readme and reading `config.def.h` for default config.
> 
> > I can run sway but it can not display the picture.just a black screen.
> > when I logined as root ,the errors disappeared，but all got into black.
> 
> Are you in the input and video groups? if not:
> 
> ```shell
> sudo usermod -aG video,input $USER
> ```

![24DD81CE-054A-4D0C-A9BE-8599B6F0E9AB](https://user-images.githubusercontent.com/86844588/158628570-9f23bb96-5e43-4bd3-864e-831163dadff1.jpeg)

Hi，bro，now I run dwl on my physical machine，but it still exists the problem
