### ISSUE TITLE
bemenu causes whole desktop to freeze up

### ISSUE THREAD

**Issue by rhogenson** [djpohly/dwl#202]
Launching bemenu with mod+p causes the mouse to freeze up and keyboard input is really delayed, or sometimes keypresses are lost altogether. The system becomes laggy and completely unusable until bemenu is closed.

I tried to debug this issue with strace, but that seemed to cause a segfault.

Typing into lxterminal also has a noticeable lag, though it's not so severe as to make the system unusable like with bemenu.

Noticed this line in the output:

```
00:00:05.454 [libinput] event8  - USB Keyboard: client bug: event processing lagging behind by 14ms, your system is too slow
```

**Comment by Sevz17** [comment]
Which version of wlroots and bemenu do you have installed?
and what commit of dwl?

**Comment by rhogenson** [comment]
wlroots is version 0.15.1, bemenu is v0.6.7, and I just cloned dwl this morning, commit 88f241d1cf54ffb7ec1f6e092ccb547c96f57ac9

I'm running NixOS unstable, and I'm using the nouveau graphics driver. I've read that wayland on nvidia is still buggy, maybe that's the reason?

**Comment by rhogenson** [comment]
I noticed I was running linux 5.4, so I upgraded to 5.15, and the issue magically went away. I guess this is some kernel bug that has since been fixed. Sorry for the noise.
