### ISSUE TITLE
Thanks for making this.

### ISSUE THREAD

**Issue by StratusFearMe21** [djpohly/dwl#207]
I know so much more about C than I used to. Messing with this compositor has been a great educational experience. So far I've implemented the fibonacci dwindle layout and vanity gaps!

**Comment by pm4rcin** [comment]
There are already patches for things you mentioned. Check [wiki](https://github.com/djpohly/dwl/wiki/Patches) for more. And if you create some interesting patches let people know so they could include it there.

**Comment by djpohly** [comment]
@StratusFearMe21 That's awesome to hear. I teach for a living, and part of what I love about the UNIX and suckless styles is how good they are for learning. Keep hacking and having fun, and definitely share your work on the wiki!

**Comment by StratusFearMe21** [comment]
I didn't even realize there was a wiki

**Comment by ahmadraniri1994** [comment]
Hi, @StratusFearMe21 , let us know if you release your patch, thanks.

**Comment by godalming123** [comment]
Why is this issue still open? shouldn't we be taking about the in the discord
