### ISSUE TITLE
More precise enter/leave for clients

### ISSUE THREAD

**Issue by djpohly** [djpohly/dwl#22]
Client surfaces should be sent enter/leave events when they enter and leave an output (monitor) in terms of being visible on that output.

Currently, these events are sent only when the client changes its "home" output `c->mon`, regardless of whether its position overlaps with other outputs as well.  This is sufficient in many common cases, but if there is a simple way to track more accurately which outputs a client is visible on, that would be an improvement.

[sway handles this](https://github.com/swaywm/sway/blob/39d677af15bd4c8cdea6b62fda80ac9a9e998045/sway/tree/container.c#L1169-L1221) by attaching a resizable array of outputs to each container.  If we could put a reasonable upper bound (of, say, 32 or 64) on the number of supported outputs and give each output an index, then we could easily use a bitset instead.

**Comment by Sevz17** [comment]
This is done by scenegraph: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/0.15/types/scene/wlr_scene.c#L170-211
