### ISSUE TITLE
MonitorRule 'x' and 'y' elements are never used; monitors cannot be consistently positioned

### ISSUE THREAD

**Issue by fauxmight** [djpohly/dwl#220]
## Info
dwl's commit: 4d3adea68325b70eafbd56a31023f96b92532b8d
wlroots version: 0.15.1
## Description

Elements 'x' and 'y' in the MonitorRule struct do not appear to ever be used.
It is not clear whether 'x' and 'y' were originally intended to indicate _position_  or _resolution_ of a monitor, but the claim in `config.def.h` that

 `The order in which monitors are defined determines their position.`

does not bear out to be true. Despite ordering three outputs (monitors) in A, B, C order in `config.h`, they are laid out in A, C, B order in reality. Changing 'x' and 'y' structure elements to match either desired position or resolution of the monitors has no effect.

**Comment by djpohly** [comment]
Ah, good catch. The `x` and `y` fields are unused and should be removed.

**Comment by fauxmight** [comment]
The above patch will close the 'x' and 'y' fields issue; I am opening a separate issue on the monitor arrangement matter.

**Comment by fauxmight** [comment]
I am closing this issue and the pull request #221 because while the 'x' and 'y' fields are not currently used, they may be in the future and probably should be.

This is discussed further in #222
