### ISSUE TITLE
Positions of multiple monitors relative to one another cannot be forced

### ISSUE THREAD

**Issue by fauxmight** [djpohly/dwl#222]
## Info
dwl's commit: 4d3adea68325b70eafbd56a31023f96b92532b8d
wlroots version: 0.15.1
## Description

`config.def.h` claims

`The order in which monitors are defined determines their position.`

In testing this with three available monitors, arranging a series of monitors in the `monrules[]` definition in "A, B, C" left-to-right order and building dwl leads to monitors arranged in "A, C, B" order.

Changing the order in the `monrules[]` definition to "A, C, B" and recompiling dwl _still_ leads to monitors arranged in "A, C, B" left-to-right (unchanged) order.

Reading through dwl.c, I do not see any obvious way to 'force' the position of the monitors. These seem to be laid out arbitrarily.

**Comment by Sevz17** [comment]
Does this make any difference?

```diff
diff --git a/dwl.c b/dwl.c
index ac62120..dc63b40 100644
--- a/dwl.c
+++ b/dwl.c
@@ -874,7 +874,7 @@ createmon(struct wl_listener *listener, void *data)
 	 * output (such as DPI, scale factor, manufacturer, etc).
 	 */
 	m->scene_output = wlr_scene_output_create(scene, wlr_output);
-	wlr_output_layout_add_auto(output_layout, wlr_output);
+	wlr_scene_output_set_position(m->scene_output, r->x, r->y);
 
 	/* If length == 1 we need update selmon.
 	 * Maybe it will change in run(). */
 ```

**Comment by fauxmight** [comment]
Nope. This led to empty black blank display on all monitors with no cursor in my case.

CAVEAT: I am running closed source nVidia drivers and using `WLR_NO_HARDWARE_CURSORS=1`
I point this out only because ANY failure I run into may be a specific to nVidia+wlroots problem

**Comment by Sevz17** [comment]
And this?
```diff
diff --git a/dwl.c b/dwl.c
index ac62120..bcc682a 100644
--- a/dwl.c
+++ b/dwl.c
@@ -875,6 +875,7 @@ createmon(struct wl_listener *listener, void *data)
 	 */
 	m->scene_output = wlr_scene_output_create(scene, wlr_output);
 	wlr_output_layout_add_auto(output_layout, wlr_output);
+	wlr_scene_output_set_position(m->scene_output, r->x, r->y);
 
 	/* If length == 1 we need update selmon.
 	 * Maybe it will change in run(). */
 ```

**Comment by djpohly** [comment]
That... wouldn't leave any way to have monitors autoconfigured, would it?

**Comment by Sevz17** [comment]
Mmm, this is before scene-graph
https://github.com/djpohly/dwl/blob/27f66c87152765942324f85be6b83d0028de295e/dwl.c#L863-L870

**Comment by fauxmight** [comment]
@Sevz17 the second change creates very odd behavior with some monitors having overlapping contents despite 'x' and 'y' values that should prohibit overlap. The cursor still moves as if there is no overlap.

However, there is no change to the arbitrary layout of the monitors. _Any_ ordering of monitors A, B and C in `monrules[]` with _any_ 'x' and 'y' values still yields an identical 'A, C, B' layout when dwl runs.

**Comment by Sevz17** [comment]
In that case... @djpohly, I'll leave this to you (if you need anything I'll try to help), I have no idea how to fix it :)

**Comment by fauxmight** [comment]
@Sevz17 Upon further testing, the first suggestion: modifying `wlr_output_layout_add_auto` to `wlr_output_layout_add` works as desired. This does make the 'x' and 'y' fields of MonitorRules useful again.

@djpohly The way the code is now, autoconfigure does set each monitor non-overlapping, but the lack of ability to specify a layout seems a greater negative than the confusion of multiple monitors positioned at 0, 0

**Comment by djpohly** [comment]
I'd recommend wlr-randr if the default autoconfigure doesn't work for you. The x and y fields should have been removed when we removed the corresponding functionality.

**Comment by fauxmight** [comment]
@djpohly Do you plan, then, to modify `createmon()` and force it to behave as described in `config.def.h` or instead remove from `config.def.h` this comment:
`/* monitors`
` * The order in which monitors are defined determines their position.`
` * Non-configured monitors are always added to the left. */`

**Comment by djpohly** [comment]
Thanks for pointing that out as well - the comment is old, from back when we weren't using wlroots' monitor configuration logic.  I've removed the vestigial fields and comment in 720f561.

**Comment by Sevz17** [comment]
Hey, you forgot remove it from the struct

**Comment by djpohly** [comment]
Thanks... hopefully I've got everything now.
