### ISSUE TITLE
Bemenu view is not updated

### ISSUE THREAD

**Issue by cantcuckthis** [djpohly/dwl#225]
## Info
dwl's commit: release 0.3
wlroots version: 0.15.0
## Description
When I run bemenu with a custom script or just bemenu-run, the view is not updated. Key presses are registered and I can use it to launch programs but nothing I type or select shows up on the bemenu. I've tried explicitly setting the BEMENU_BACKEND variable to wayland but to no avail. Should I open this issue at bemenu's github page instead?

**Comment by Sevz17** [comment]
Update to wlroots-0.15.1

0.15.0 is buggy, you should have problems with firefox too

**Comment by cantcuckthis** [comment]
Solved! Thank you!
