### ISSUE TITLE
cannot click into the save as dialog in geogebra 

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#231]
## Info
dwl's commit: c00697e6438164e08baacc309b3dcdb727053aeb  Apr.5 2022
wlroots version: 0.15.1
## Description
in geogebra which use Xwayland i think, i cannot click the "cancel" button in dialog such as "save as". Actually, the touch pad left button does not work for any of the clickable area on the dialog.  i can close the dialog with ESC key.

it works fine in DWM.  

![20220504_20h23m14s_grim](https://user-images.githubusercontent.com/12045548/166682111-6ea09402-693c-4917-a331-58b32c940419.png)

BTW, to use geogebra in DWM or DWL, i have to `export _JAVA_AWT_WM_NONREPARENTING=1`  as described in https://help.geogebra.org/topic/no-gui

**Comment by PalanixYT** [comment]
Possibly related, the lol client also cannot be interacted with.

**Comment by guyuming76** [comment]
some progress in my test: if somehow, the red rectangle around geogebra main windows does not switch onto the "save as" dialog, the mouse button on the dialog will work.

but i don't know how to reproduce, it just happened this morning when i tried to open geogebra to see it says not being able to connect to x11 with DISPLAY :0.  I checked with htop and found no Xwayland process.  So i just typed Xwayland in a bash prompt, and a black window appear. I opened geogebra from another bash prompt, it showed up in the black window as following screenshot, and the "save as" worked, the difference was that there was no red rectangle around the "save as" dialog.  But i cannot reproduce it now, and i don't know the theory underneath.  

Also i am not sure if this is a bug that can be fixed or something impossible or something better to be handled by java awt or geogebra or wlroots or else.

![20220505_07h13m23s_grim](https://user-images.githubusercontent.com/12045548/166841572-d804dc61-d0f8-42aa-b42d-d9ddc61140be.png)

**Comment by guyuming76** [comment]
seems that if i toggle floating with mod+shift+space, i can click into the "save as" dialog.

What follows is the "save as" dialog that i cannot click into:
![20220505_15h23m14s_grim](https://user-images.githubusercontent.com/12045548/166878627-7e465dfe-4dc0-477e-9a5d-34c7ca5e1ff4.png)


After toggle floating, i can click the cancel button:
![20220505_15h23m37s_grim](https://user-images.githubusercontent.com/12045548/166878812-1c6bc63a-34fd-4ae7-8b5c-c8129ac266c7.png)

**Comment by guyuming76** [comment]
with xwininfo and xprop, i can see that when i cannot click into the "save as" dialog, i actually clicked into other other window in xwindow:
![20220505_16h09m33s_grim](https://user-images.githubusercontent.com/12045548/166886123-5d460988-1870-48be-b997-aab23189fbbb.png)


After toggle floating, i can see that the "save as" dialog is named "Save" in xprop:
![20220505_16h10m03s_grim](https://user-images.githubusercontent.com/12045548/166886370-057c0463-de16-475e-ab0f-ec3749da8e1d.png)

**Comment by guyuming76** [comment]
When Xwayland gets a pointer event on a window, it doesn't send it directly to that window. Instead, it converts the location to screen coordinates and then pushes the event through the old X event handling mechanism, which looks at the X11 window stack to decide where to send it.

However, the X11 window stack (which we saw earlier with xwininfo -tree -root) doesn't correspond to the Wayland window layout at all. In fact, Wayland doesn't provide us any way to know where our windows are, or how they are stacked.  

from https://roscidus.com/blog/blog/2021/10/30/xwayland/#pointer-events

Seems to explain what i am experiencing.

**Comment by guyuming76** [comment]
the Xorg server can be modified to use wayland input devices for input and forward either the root window or individual top-level windows as wayland surfaces.  
from https://wayland.freedesktop.org/xserver.html

i see that xwayland started by dwl has --rootless argument, is it possible to configure it otherwise?

**Comment by PalanixYT** [comment]
Hm, this sounds like it's already fixed. Can you update to the newest version to check if it's still there?

**Comment by guyuming76** [comment]
@PalanixYT, thanks,  i just see https://github.com/djpohly/dwl/commit/3a4b7d104ff8bfc14862b7e41bcacb35677306a4 

it seems to be corresponding to what follows from https://roscidus.com/blog/blog/2021/10/30/xwayland/#pointer-events

Sommelier has a solution though: when the pointer enters a window we raise it to the top of the X11 stack. Since it's the topmost window, it will get the events.


it fixed the geogebra dialog behavior for me. But the article i referenced also talks about some synchronization related issue for this solution which i do not quite understand now.

**Comment by Sevz17** [comment]
> it seems to be corresponding to what follows from https://roscidus.com/blog/blog/2021/10/30/xwayland/#pointer-events
> 
> _Sommelier has a solution though: when the pointer enters a window we raise it to the top of the X11 stack. Since it's the topmost window, it will get the events._
> 
> it fixed the geogebra dialog behavior for me. But the article i referenced also talks about some synchronization related issue for this solution which i do not quite understand now.

When I have free time I will read it, I leave this open to remind myself to read it.
