### ISSUE TITLE
autostart patch fail

### ISSUE THREAD

**Issue by adcdam** [djpohly/dwl#237]
i can not apply this patch for version 0.3.1
https://github.com/djpohly/dwl/compare/main...fauxmight:autostart.patch

 it say: 

```
Hunk #1 succeeded at 210 (offset -9 lines).
Hunk #2 succeeded at 375 (offset -5 lines).
Hunk #3 succeeded at 396 (offset -5 lines).
Hunk #4 succeeded at 1650 (offset 32 lines).
Hunk #5 succeeded at 1754 with fuzz 1 (offset -102 lines).
Hunk #6 FAILED at 2189.
1 out of 6 hunks FAILED -- saving rejects to file dwl.c.rej
patching file config.def.h
```

**Comment by fauxmight** [comment]
I merged mainline into the autostart branch earlier today (before you had posted this issue).
I am able to merge autostart without issue to both the 'main' branch of this repo and the 'v0.3.1' branch.

Please try this once more and report back here if you still run into troubles.

**Comment by fauxmight** [comment]
@adcdam: If you are downloading the patch file and manually applying it, I see that `patch < autostart.patch` does indeed fail.

Use this method instead, allowing git's more advanced merging mechanism to do the job:

```
git clone https://github.com/djpohly/dwl.git
cd dwl
git remote add fauxmight https://github.com/fauxmight/dwl.git
git fetch fauxmight
git merge fauxmight/autostart
```

**Comment by adcdam** [comment]
thanks!,  that way i was able to patch it, are you going to make a release with that? i hope there is a release soon so i can make a package with that, instead of patching the git version.

**Comment by fauxmight** [comment]
@adcdam: I am a contributor with my own fork of this repository, but I am not a mainline developer of dwl. The autostart capability was originally worked out from [dwm](https://dwm.suckless.org/) code by @Sevz17 who, along with @djpohly, IS a mainline developer of dwl.

I strongly suspect that autostart will **not** be something pushed to a mainline release as this is not a fundamental feature of dwl and would seem to me to be the sort of thing that belongs where it is in the user-contributed patches.

Perhaps @Sevz17 will chime in here and confirm or deny that suspicion.
Now that you have a solution to the original trouble, I will close this issue after a week or after @Sevz17 lets us know a firm answer on your secondary question, whichever comes first.

**Comment by Sevz17** [comment]
@adcdam autostart won't merge to mainline, because as @fauxmight said, dwl works fine without it, but I'll reconsider merging it if the dwm folks merge it as well.

**Comment by pigeon46** [comment]
> @adcdam: If you are downloading the patch file and manually applying it, I see that `patch < autostart.patch` does indeed fail.
> 
> Use this method instead, allowing git's more advanced merging mechanism to do the job:
> 
> ```
> git clone https://github.com/djpohly/dwl.git
> cd dwl
> git remote add fauxmight https://github.com/fauxmight/dwl.git
> git fetch fauxmight
> git merge fauxmight/autostart
> ```

How do I do this when I already have dwl set up good and proper on my own dotfiles repo?

**Comment by fauxmight** [comment]
@pigeon46:

Option 1) Use git to make the above modifications. Remember to adjust config.h accordingly. Test. Push this finished, usable, but static and soon stale build into your  dotfiles repo.

Option 2) [The right way : )  ] Become comfortable with git. Fork this repo. Clone a local copy of your fork, add the forks that have patches (like autostart) that you want to use as additional remotes in your local fork and merge those changes. Keep your fork and your local copy up to date since dwl is under heavy development and neat progress is made on various aspects each week!

**Comment by pigeon46** [comment]
@fauxmight 

I will do option 2 then. But I have a question. Can I make it so that when I clone my dotfiles repo, it also clones my forked dwl repo within it?
