### ISSUE TITLE
Keybinds Not Working in dwl

### ISSUE THREAD

**Issue by kawaiiamber** [djpohly/dwl#239]
## Info
dwl's commit: 8870ba0bb8106a4a367bd8dee78178891b8c19db
wlroots version: 0.15.1
## Description

Distro: VOID-musl

Starting `dwl` from a tty results in a black screen and a black cursor. None of the keybinds in `config.h` work - including the one to exit dwl, another tty must be used to kill dwl: `kill $(pidof dwl)`. No errors or warnings durring build.

Closest related issues: [#113 ] [#67]

**Comment by Sevz17** [comment]
The black screen is perfectly normal.
So, about the keybindings not working, are you in the input group?

**Comment by kawaiiamber** [comment]
Same behaviour after: `doas usermod -a -G input amber`. I don't know what being "able to switch between vts" means

**Comment by Sevz17** [comment]
I meant, are you able to switch to another tty?

**Comment by kawaiiamber** [comment]
Yes. As mentioned above, it was the only way to kill `dwl` with `kill $(pidof dwl)`

**Comment by Sevz17** [comment]
Then the keybinding work, switch to another tty is configured via [config.h](https://github.com/djpohly/dwl/blob/main/config.def.h#L106-L110), maybe you need to reconfigure your keybindings, I guess your keyboard layout is different from US layout, isn't it?

**Comment by kawaiiamber** [comment]
No, it is us keymap. I use the default `config.h` - no changes. Directly as it comes.

**Comment by pm4rcin** [comment]
By default `alacritty` is used as terminal. So if you don't have it installed then you can't start it. Make sure that you have it.

**Comment by kawaiiamber** [comment]
> By default `alacritty` is used as terminal. So if you don't have it installed then you can't start it. Make sure that you have it.

Yes, both alacritty and bemenu are installed - `alacritty` and `bemenu-run` are successfully installed in the system `PATH`, and I'm using the default values `termcmd` and `menucmd` in `config.h`. They work in other wayland environments such as sway. Issue persists. I don't know if there's supposed to be a basic status bar at the top showing the different tags like in `dwm`, but that also isn't there. It's quite literally all black with just a mouse. I can, however, switch to another `tty`.

**Comment by pm4rcin** [comment]
There's no built-in bar. Are you aware that default Modkey is alt like in dwm? Also could you check if dwm works for you?

**Comment by kawaiiamber** [comment]
> There's no built-in bar. Are you aware that default Modkey is alt like in dwm? Also could you check if dwm works for you?

Yes, I am aware default value for `Modkey` is alt. Yes, my build of `dwm` works with `xinit`.

**Comment by kawaiiamber** [comment]
Fixed after editing `dwl.c` for a bit.

**Comment by pm4rcin** [comment]
Could you tell what was wrong so we can redirect people who'll have similiar problem in the future?

**Comment by kawaiiamber** [comment]
> Could you tell what was wrong so we can redirect people who'll have similiar problem in the future?

I don't think others will have this issue. It was something weird on my setup.
