### ISSUE TITLE
Update the wiki to allow patches per dwl version

### ISSUE THREAD

**Issue by sevz17** [djpohly/dwl#252]
I think in something like this
\=================

#### Description
Allow dwl to execute commands from autostart array in your config.h file. And when you exit dwm all processes from autostart array will be killed.

#### Example
```c
static const char *const autostart[] = {
	"foot", "--server", NULL,
	"fnott", NULL,
	NULL
};
```

#### Attention
Commands from array are executed using execvp(). So if you need to execute shell command you need to prefix it with "sh", "-c" (change sh to any shell you like).

#### Download
[git](https://github.com/djpohly/dwl/compare/main...Sevz17:autostart.patch)
[wlroots-next](https://github.com/djpohly/dwl/compare/wlroots-next...Sevz17:autostart-wlroots-next.patch)
[v0.3.1](https://pastebin.com/raw/09Lmaew7)

**Comment by sevz17** [comment]
WIP: https://github.com/sevz17/dwl/wiki

**Comment by fauxmight** [comment]
This template looks great.

**Comment by Ogromny** [comment]
Any update on this issue ?

**Comment by sevz17** [comment]
No, I haven't had enough time to work on this, and no one seems to have started to work on this, or  shared their work.

**Comment by dm1tz** [comment]
I made a somehow ready layout for the wiki. If everyone is satisfied with it I can start moving it to the main wiki and gradually updating the patches. Here's the [link](https://github.com/dm1tz/dwl/wiki). Looking forward to your feedback.

**Comment by sevz17** [comment]
Hi @dm1tz, that looks amazing!, just a few comments
- I don't mind sharing my email, but there may be people who do (even if they use their real address in commits)
- related to the previous one, add something like this: `... then create a new page on the wiki using this example (you can add or remove sections as you like):`
- please `s/Sevz17/sevz/`

**Comment by dm1tz** [comment]
> Hi @dm1tz, that looks amazing!, just a few comments
> 
> * I don't mind sharing my email, but there may be people who do (even if they use their real address in commits)

Agree, I will remove email part.
> * related to the previous one, add something like this: `... then create a new page on the wiki using this example (you can add or remove sections as you like):`
> * please `s/Sevz17/sevz/`

Will do. So may I start moving this template to the main wiki? Btw, I was thinking about overhauling the README a bit, for example we can move status information section to the wiki and mention the link to that instead.

**Comment by sevz17** [comment]
> So may I start moving this template to the main wiki?

Sure

> Btw, I was thinking about overhauling the README a bit, for example we can move status information section to the wiki and mention the link to that instead.

I'd like to keep that info in the README, but we can move the external bars to the wiki.

**Comment by dm1tz** [comment]
> > So may I start moving this template to the main wiki?
> 
> Sure
> 
> > Btw, I was thinking about overhauling the README a bit, for example we can move status information section to the wiki and mention the link to that instead.
> 
> I'd like to keep that info in the README, but we can move the external bars to the wiki.

All done. Created a PR [here](https://github.com/djpohly/dwl/pull/299).

**Comment by sevz17** [comment]
Many thanks
