### ISSUE TITLE
Support for dpms

### ISSUE THREAD

**Issue by magnouvean** [djpohly/dwl#254]
I might be missing something, but I have had a hard time turning my displays off through a command (something like `xset dpms force off` on xorg). `wlr_randr` works for turning the displays off, but it is unable to turn off both of my screens (when I turn the last one off the other one for some reason turns on). `swaymsg output * off` unsuprisingly doesn't work either. I also found [dpms-off](https://github.com/lilydjwg/dpms-off) which does exactly what I want, but it doesn't work as it requires `zwlr_output_power_manager_v1` to be implemented. Is there any way to turn off all the screens through for instance `swayidle`? If it isn't possible would it be possible to implement `zwlr_output_power_manager_v1` to make dpms-off work (`org_kde_kwin_idle` which is the other required interface seems to be implemented so everything else seems to work).

**Comment by fauxmight** [comment]
`swaymsg "output * dpms off"` seems to work correctly.

**Comment by magnouvean** [comment]
Hmm, weird. This doesn't seem to work on my machine. When I run `swaymsg 'output * dpms off'` here I get the following error:
`[swaymsg/main.c:419] Unable to retrieve socket path`
I have gotten this before when running inside tmux, but the problem seems to persist even without this. I also tested the same command inside sway to confirm it works and it seems fine there.

**Comment by fauxmight** [comment]
Hm. Me too. This has worked properly in the past. Working on a better answer for you.

**Comment by fauxmight** [comment]
@magnouvean It appears that using `swaymsg ... dpms ...` is out of the question. The requires the full sway socket setup that is never going to be ported into dwl.

An alternative is [dpms-off](https://github.com/lilydjwg/dpms-off) as you have noted.
Making this work in dwl will require:
- adding [wlr-output-power-management-unstable-v1.xml](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-output-power-management-unstable-v1.xml) which seems to have been removed from the active upstream wlroots at the freedesktop.org [git repo](https://gitlab.freedesktop.org/wlroots/wlr-protocols)
- Adding `#include <wlr/types/wlr_output_power_management_v1.h>` to dwl.c
- Adding `wlr-output-power-management-unstable-v1-protocol.h` to the end of the `dwl.o` line in the `Makefile`
- Adding 
  `wlr-output-power-management-unstable-v1-protocol.h:`
  `      $(WAYLAND_SCANNER) server-header`
  `             protocols/wlr-output-power-management-unstable-v1.xml $@`
 to the `Makefile`

And THEN doing the hard work of actually implementing output-power-management-unstable-v1-protocol functions in `dwl.c`

... in case this is worth your time to add as a patch, there's an starter.
I don't know that this will be mainline addressed any time soon, but one of the more core developers may well add more fitting details here.

**Comment by Sevz17** [comment]
There is a patch for that, see the patches page

**Comment by fauxmight** [comment]
@Sevz17 Thanks. I only searched the wiki for "dpms" and missed that.

**Comment by magnouvean** [comment]
Ah I missed that one as well. Well after applying the output-power-management patch dwl works fine with `dpms-off`. There still seems to be some twitching when turning the screen back on, but I see there is a seperate issue about that. Thanks for the help guys :)
