### ISSUE TITLE
to avoid unnecessary duplicate printstatus output

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#258]
I made a change to avoid unnecessary duplicate printstatus: 

https://gitee.com/guyuming76/dwl/commit/1890ab1422a7d38e562f1030e46a49cbdd7b9c85

Since my waybar read from the printsatus output to display tags bar, it will improve performance a little bit i think and make "the log" more readable.

I should have create a pull request, but i get some issue pushing to github, something related to the personal token.

**Comment by Sevz17** [comment]
If you can't create a pr, could you send me the patch through email (leohdz172@protonmail.com)?

**Comment by sevz17** [comment]
I replied in email, but also need to reply this, this patch doesn't belong to the main branch, thus I cannot merge it.
