### ISSUE TITLE
imv maxes all CPU cores

### ISSUE THREAD

**Issue by fauxmight** [djpohly/dwl#260]
## Info
dwl's commit: c1578bc14db7822743ffdbde93b2c22b1a0b5f6a
wlroots version: 0.15.1
## Description
Running [imv](https://sr.ht/~exec64/imv/) which *is* running as a native wayland client (verified with xeyes) maxes out all CPU cores for as long as imv runs.
This does not happen running imv under sway.

**Comment by sevz17** [comment]
Does this also happens in [tinywl](https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/0.15/tinywl)?

**Comment by sevz17** [comment]
Forget it, I know why this happens.

**Comment by fauxmight** [comment]
> Does this also happens in [tinywl](https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/0.15/tinywl)?

No. It does not happen in tinywl, but tinywl only builds on wlroots-git, and I am running wlroots-0.15.1 (latest stable at the time of writing).

**Comment by sevz17** [comment]
It happens because https://github.com/djpohly/dwl/blob/main/dwl.c#L791-L792
