### ISSUE TITLE
XWayland does not grab mouse

### ISSUE THREAD

**Issue by irishgreencitrus** [djpohly/dwl#265]
## Info
dwl's commit: 87fc3a58ab72ff6ff6eb6e1156ff208fcb9e3739
wlroots version: 0.15.1
## Description
XWayland windows do not grab the mouse properly.
In first person games and the like, the mouse is hidden however can still be moved outside of the window.
This issue is not apparent in sway, as i have tested

**Comment by sevz17** [comment]
What you want is pointer constraints, there are a patch for it in the [patches page](https://github.com/djpohly/dwl/wiki/Patches)

**Comment by fauxmight** [comment]
@irishgreencitrus: The pointer constraints patch does not apply cleanly against current git. I expect to have that resolved again soon.

@sevz17: Is there a reason that pointer constraints is "not planned" to be merged?

**Comment by sevz17** [comment]
> @irishgreencitrus: The pointer constraints patch does not apply cleanly against current git. I expect to have that resolved again soon.

I copied the implementation of sway into dwl but I never pushed it to github :) (https://github.com/sevz17/dwl/tree/pointer-constraints)

> @sevz17: Is there a reason that pointer constraints is "not planned" to be merged?

Too much code (~80 lines in [wiki's patch](https://github.com/djpohly/dwl/compare/main...PalanixYT:point.patch) and ~250 lines in [my implementation](https://github.com/sevz17/dwl/commit/de6bec75404c549c73b80248a19b8f6b695f5ef6.patch))

**Comment by fauxmight** [comment]
@sev17: Well thanks! I've been fighting with the one from @PalanixYT for ages. His is great, but he does not get a lot of time to merge PR's to his repo to keep it in line with upstream.

**Comment by PalanixYT** [comment]
It's not my impilementation, I simply started mainaining it. Sadly I still use gmail and gmail recently disabled "insecure passwords" and now I can't reach my email.

**Comment by PalanixYT** [comment]
it's updated now
