### ISSUE TITLE
can i use wlr-randr to set display mode in startup script?

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#266]
after i started dwl and connect my laptop to projector with HDMI, i can use wlr-randr commands to set the display mode of the projector , and set it to duplicate the laptop screen output.

 ```
     wlr-randr --output HDMI-A-1 --mode 1360x768
     wlr-randr --output HDMI-A-1 --pos 0,0
```

but if i put the wlr-randr commands into the script used by dwl -s , the wlr-randr does not work, or even dwl fails to start.

so, is it that my use of wlr-randr in the start script not correct? what's the correct way? or it is the current limitation of the start script?

**Comment by guyuming76** [comment]
i figured out:

wlr-randr should be run after wl_display_run,i.e, after the wayland event loop started.

so, in my script which contains wlr-randr, i added a sleep 10 and it works now.

**Comment by fauxmight** [comment]
If you are content with your solution, please close the issue.
