### ISSUE TITLE
After using "wtype", windows don't lose focus when new windows are focused

### ISSUE THREAD

**Issue by BenJarg** [djpohly/dwl#270]
For example, to reproduce, after running `wtype "appleapple"; wtype -k Tab` then moving the mouse from one window to a window on another monitor, all the windows the moused passed in between keep focus. I.e., multiple windows end up being highlighted, and when I start typing the window receiving text isn't the window currently under the mouse. This is with sloppy focus enabled.

This seems to be caused by 8e03bce6217117f0687cd727ae2c47bdd3c0fe5a. Reverting this solves the issue for me.

**Comment by sevz17** [comment]
Interesting, that commit shouldn't cause focus problems.
