### ISSUE TITLE
Crash when switching librewolf fullscreen

### ISSUE THREAD

**Issue by pm4rcin** [djpohly/dwl#274]
## Info
dwl's commit: 8cdb9971264adfdc35777b5a9935c2e4c47eea9f+[Autostart](https://github.com/djpohly/dwl/compare/main...Sevz17:autostart.patch)+[Pointer Constraints](https://github.com/sevz17/dwl/commit/de6bec75404c549c73b80248a19b8f6b695f5ef6.patch)
wlroots version: 0.15.1
XWayland enabled
## Description
When I click ModKey+e  several times in librewolf then the whole compositor crashes to tty. And also in tty there's prompt that runs continuously and says "cannot open file or directory" and the only thing I can do is to use ctrl-d because ctrl+c doesn't work.
## Log
[dwllog.log](https://github.com/djpohly/dwl/files/9174275/dwllog.log)

**Comment by fauxmight** [comment]
@pm4rcin What is in the autostart segment of config.h?

**Comment by sevz17** [comment]
can you check if #275 fixes this issue?

**Comment by sevz17** [comment]
> @pm4rcin What is in the autostart segment of config.h?

I believe `cannot open file or directory` is a message from someblocks

**Comment by pm4rcin** [comment]
> can you check if #275 fixes this issue?

It has fixed the issue :)

> I believe `cannot open file or directory` is a message from someblocks
You're right.
