### ISSUE TITLE
increase the limit of SLOC

### ISSUE THREAD

**Issue by sevz17** [djpohly/dwl#278]
We are running out of lines (at b04c73be3de62d2739b5bb85e40f0c9af1122903 tokei reports exactly 2000 SLOC)

So the question is: does anyone really need it?

**Comment by pm4rcin** [comment]
Could you tell what is that, preferably with an example? I've only read that it's something related to notifications but I can't find a good example of usage.

**Comment by djpohly** [comment]
I like to have my windows ask for attention in a simple fashion, without having to go through a heavyweight or intrusive notification manager. The urgency hint has always been the way dwm handles it, quietly highlighting the tag of a window requesting attention.

**Comment by sevz17** [comment]
On discord some users also disagree with this...

@djpohly we need to increase the limit of SLOC, even with wlroots we need to handle things that dwm don't have to, i.e create two types of clients (layer shell and normal clients (xdg and xwayland), implement protocols analogous to those provided by the X server, etc.
and another thing I think we really should support is touch...

**Comment by pm4rcin** [comment]
@sevz17 what's the use case for touch support because I don't get why we need touch in a tiling WM?

**Comment by djpohly** [comment]
I'm not against increasing the SLOC limit, but it's there so we make careful decisions about what is in mainline and what is a patch.  Touchscreen support feels like patch territory to me.  If you consider all the systems that might run dwl, there may be many with touchscreens, but I wouldn't say it's the vast majority.

Is there something more universally applicable being held back by the SLOC cap?

**Comment by pm4rcin** [comment]
> I'm not against increasing the SLOC limit, but it's there so we make careful decisions about what is in mainline and what is a patch. Touchscreen support feels like patch territory to me. If you consider all the systems that might run dwl, there may be many with touchscreens, but I wouldn't say it's the vast majority. (I'm writing this from a laptop with a touchscreen, so it's not because I wouldn't use it!)
> 
> Is there something more universally applicable being held back by the SLOC cap?

I think that https://github.com/djpohly/dwl/pull/226 is universal and should be implemented. And that's definitely held back.

**Comment by sevz17** [comment]
> Is there something more universally applicable being held back by the SLOC cap?

I think mainly getting wlr-randr working, correctly implementing the idle inhibit protocol, ext-session-lock and general bug fixes (eg https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3653 , etc.)
