### ISSUE TITLE
SIGSEGV on right click in Telegram Desktop

### ISSUE THREAD

**Issue by geekylthyosaur** [djpohly/dwl#281]
## Info
dwl's commit: [9d2eb84](https://github.com/djpohly/dwl/commit/9d2eb8483b52a7a4858454d557196d83e1a24011)
wlroots version: 0.15.1
## Description
In Telegram Desktop right clicking where the menu might appear, dwl crashes with `SIGSEGV (Address boundary error)`
Telegram reports: `The Wayland connection broke. Did the Wayland compositor die?`
This issue does not apply to Sway, Wayfire, Weston.
Enabling XWayland, setting `QT_QPA_PLATFORM=wayland` - does not make any difference.
[anvil](https://github.com/Smithay/smithay/tree/master/anvil) handles right click menu right _however_ crashes on scroll.
I use [musl](http://musl.libc.org/) if that matters.

**Comment by sevz17** [comment]
662e06e68e9bc2c41c3cb90d36c4d9998ff1f958 should fix this, if it doesn't, feel free to reopen this issue
