### ISSUE TITLE
Starting terminal in dwl causing fish autostart script for plasma session to be evoked

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [djpohly/dwl#286]
dwl's commit: dwl 0.3.1-662e06e
wlroots version: wlroots 0.15.1-6
OS : Archlinux
I have a fish script for autostarting plasma when logged into tty.
But when I log out of plasma and manually start dwl from tty, the script is being evoked from dwl whenever I open a  terminal, causing a nested plasma session to appear inside dwl. This does not happen on other wlroots compositors like wayfire, Hyprland, or river.

This is my fish script, 

```
if status is-interactive
    if test -z "$DISPLAY" -a "$XDG_VTNR" = 1
	sleep 1
        dbus-run-session startplasma-wayland &> /dev/null
    end
end
```
Is this a bug?

**Comment by sevz17** [comment]
your script only check if $DISPLAY is set (for x11 apps) so the problem is you are not compiling dwl with xwayland support (that sets DISPLAY), I recommend you to check also $WAYLAND_DISPLAY or compile dwl with xwayland support.

**Comment by sevz17** [comment]
ah, also you should check that `$TTY` or `$(tty)` equals to `/dev/tty1` instead of checking `$XDG_VTNR`
