### ISSUE TITLE
Trying to use `XWAYLAND` from `config.mk` fails

### ISSUE THREAD

**Issue by HanoJing** [djpohly/dwl#304]
## Info
dwl's commit: 9bcef3d
wlroots version: 0.15.1
## Description
Trying to use `XWAYLAND` from `config.mk` fails with:
https://dpaste.com/2SRATMLGJ

Many thanks.
regards,
HanoJing

**Comment by sevz17** [comment]
One of your patches do not replace all occurrences of `VISIBLEON()` to `VISIBLEONTAG()`

**Comment by HanoJing** [comment]
Thanks a lot for the quick reply, I'll be sure to look into it.
