### ISSUE TITLE
X11 Dropdown Menus Do Not Retain Focus

### ISSUE THREAD

**Issue by alex-courtis** [djpohly/dwl#31]
Dropdowns lose focus and disappear when they are over another window.

Reproduce:
- Open chromium to the left of another window
- Click the menu
- Hover over history item
- Move the mouse over the history menu which is over the other application

(I'd label this but do not have permissions)

**Comment by djpohly** [comment]
This would technically be "fixed" by #34, though probably not in the way you'd assume.  That could be remedied by #35, though probably not in the way you'd assume. :smile:

**Comment by alex-courtis** [comment]
This one is tricky:

Experimentation indicates that focussing the independent itself renders it unresponsive. It seems they don't like to / expect to be focussed.

Having motionnotify retain the focus on selclient() (hacky) does result in a responsive independent, but only an long as the focus is over selclient(). The menu will remain present as long as the mouse is over it, just the bits over other windows don't... work.

**Comment by alex-courtis** [comment]
Fortunately, we can directly focus independents... providing you remember that `geom` is 00 for independents.

WIP: https://github.com/alex-courtis/dwl/commits/31-independents-mouse-focus

TODO:
- firefox / chrome hamburger menus dissapear the first time you click on them
- restrict independents to those actually visible: perhaps use the "owning" client's current monitor

**Comment by alex-courtis** [comment]
All resolved in https://github.com/djpohly/dwl/pull/37

**Comment by tauin** [comment]
so shouldn't this be closed?
