### ISSUE TITLE
Active border bug when using a launcher like bemenu/rofi/etc.

### ISSUE THREAD

**Issue by vacuumbeef** [djpohly/dwl#310]
## Info
dwl's commit: [fc8b2a8](https://github.com/djpohly/dwl/commit/fc8b2a8335365dbf3966f0a9bb783a4cb33fdcbf)
wlroots version: 0.15.1-6
## Description

When you toggle a launcher (for example bemenu), and move a cursor, all windows under cursor will have an active window border at the same time. And it will persist after launcher is closed
Here is an example video:

https://user-images.githubusercontent.com/51813411/192608993-29bc855d-24ff-4c9e-bd4d-32b53b2e20ac.mp4

.

**Comment by sevz17** [comment]
It was fixed time ago (I don't remember the specific commit), do you have external patches?, if so, can you reproduce in plain main branch?

**Comment by vacuumbeef** [comment]
You know what, I'm sorry, my bad. I thought that I am using dwl compiled by myself, but actually I already had dwl from AUR. Everything is good on main branch, sorry.
