### ISSUE TITLE
Relative pointer protocol

### ISSUE THREAD

**Issue by sewe2000** [djpohly/dwl#313]
Hello everyone!
Are there any plans of supporting wayland relative pointer protocol, so I could play some games?
My problem is the movement of the mouse on the X axis is flipped in Garry's mod. Also I can't move the camera more than by 180 degrees ( 3.14 rad).
I suspect it's a dwl issue.
Thank you in advance.

**Comment by sewe2000** [comment]
Alternatively, are there any patches that I can apply for this functionality?

**Comment by sevz17** [comment]
> Alternatively, are there any patches that I can apply for this functionality?

Yes, there are https://github.com/djpohly/dwl/wiki/pointerConstraints and https://github.com/djpohly/dwl/wiki/Pointer-constraints-(mostly-copied-from-sway), both are mutually exclusive.

**Comment by sevz17** [comment]
Duplicate of: #265
