### ISSUE TITLE
Clients' borders aren't drawn correctly during drag and drop

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#318]
i use https://github.com/padgettr/rfm  to manage my pictures. In DWM, i can open two instances of rfm and copy/move pictures between them with drag and drop. But it does not work in DWL. why? is it something with wlroots/dwl or gdk/gtk?

when i *drop* in DWM, i can see handler in rfm called as shown in the screenshot. But in DWL, the handler is not called. 

And in DWL, the handler for *drag* is called when i start dragging. 

![rfmDnd_DWM_drop1](https://user-images.githubusercontent.com/12045548/194477727-6d6fac61-940e-4d4d-b578-dcae47a24373.png)

in dwl log, i can see what follows. looks like rfm is working with xwayland? it is based on gtk+, does it works with wayland natively?

```
00:02:10.006 [DEBUG] [types/wlr_surface.c:748] New wlr_surface 0x10831b0 (res 0x10cdd60)
00:02:10.008 [DEBUG] [types/wlr_surface.c:748] New wlr_surface 0x10af9b0 (res 0x10ceae0)
00:02:10.008 [DEBUG] [types/data_device/wlr_data_source.c:189] Offering additional MIME type after wl_data_device.set_selection
00:02:10.008 [DEBUG] [types/data_device/wlr_data_source.c:196] Ignoring duplicate MIME type offer text/uri-list
00:02:10.008 [DEBUG] [types/data_device/wlr_data_source.c:189] Offering additional MIME type after wl_data_device.set_selection
00:02:10.009 [DEBUG] [xwayland/selection/incoming.c:486] XCB_XFIXES_SELECTION_NOTIFY (selection=298, owner=2097155)

```
I tried rebuilding dwl without xwayland, and drag and drop again. Now, the last entry in the logs above disappear, but drop still has no effect.

**Comment by sevz17** [comment]
With the last commit drag and drop should working fine now, I didn't close the issue because still there are problems with the clients' border color

**Comment by guyuming76** [comment]
it looks like [commit b8bc54b65d7dfaf1c7aa92de32f8ca37d8e011f9](https://github.com/djpohly/dwl/commit/b8bc54b65d7dfaf1c7aa92de32f8ca37d8e011f9) breaks the DnD, it works before.

**Comment by sevz17** [comment]
https://github.com/djpohly/dwl/commit/f6820a6c29b6bcb9a14166793d7f1fba2f98444e didn't fix the issue?

**Comment by guyuming76** [comment]
> [f6820a6](https://github.com/djpohly/dwl/commit/f6820a6c29b6bcb9a14166793d7f1fba2f98444e) didn't fix the issue?

sorry, i need to try again. there is something wrong with my git merge.
