### ISSUE TITLE
TrackPoint in Minetest behaves weird

### ISSUE THREAD

**Issue by Geronymos** [djpohly/dwl#325]
## Info

dwl's commit: e9826de2959609f597bc80137183828562315c14
wlroots version: 0.15.1-6

## Description

When playing Minetest with a TrackPoint (my laptop only has a TrackPoint; it is my preferred input method ) on dwl the sensitivity is way to high and the controls don't make sense: tilting left/right also results in up/down movement. 

I have to resort to Sway in another tty just to have sane controls. I haven't done any patches other than keybindings to my dwl. 

Maybe Sway does something different with the input devices that could be ported to dwl? I know that this is really a niche issue but it might also effect other applications. I really would appreciate a fix since playing Minecraft is no options for me since Microsoft forced their Accounts on it.

**Comment by sevz17** [comment]
Mmm, please try either https://github.com/djpohly/dwl/wiki/pointerConstraints or https://github.com/djpohly/dwl/wiki/Pointer-constraints-(mostly-copied-from-sway)

**Comment by Geronymos** [comment]
Thanks. I tried both patches. The first one seems more simple, but the acceleration to too strong for my taste. The one that is mostly copied from sway works great. The only problem is that when Minetest releases my cursor (open inventory/settings) my cursor appears on my second monitor and I have to move it back to the game. 

Now that I know the name of the problem (pointer constraint) I see that this is an actively discussed topic https://github.com/djpohly/dwl/issues/317. I hope my feedback helps implementing a solution that benefits everyone ^^ 
Keep up the great work!

**Comment by sevz17** [comment]
Duplicated of #317.
