### ISSUE TITLE
wlr_gamma_control_unstable_v1 protocol

### ISSUE THREAD

**Issue by m00nwtchr** [djpohly/dwl#332]
This allows "night mode" applications like redshift to work, not asking for it to be added to dwl itself, but it would be nice to have as a patch.

May try to do it myself, but i haven't really ever done anything with wlroots etc.

**Comment by sevz17** [comment]
It is actually part of dwl, https://github.com/djpohly/dwl/blob/main/dwl.c#L2116

**Comment by m00nwtchr** [comment]
Ah, I didn't get anything in github search for some reason.
