### ISSUE TITLE
xwayland undeclared error while compiling

### ISSUE THREAD

**Issue by ephemer4l** [djpohly/dwl#348]
## Info
dwl version: 0.4-r1
wlroots version: 0.16
## Description
I get the following error when trying to compile dwl-0.4-rc1 **without** -DXWAYLAND
```
dwl.c: In function ‘sigchld’:
dwl.c:2300:41: error: ‘xwayland’ undeclared (first use in this function)
 2300 |                         && in.si_pid != xwayland->server->pid) {
      |                                         ^~~~~~~~
```

How to go about fixing this?

**Comment by sevz17** [comment]
sigchld is guarded by `#if`'s.

This caused by one of your patches.

**Comment by fauxmight** [comment]
This function is wrapped in an `#ifdef XWAYLAND ... #endif`
AND, this function is at line 2532.
You're not actually compiling 0.4-rc1

**Comment by sevz17** [comment]
Can you send me the content of sigchld?, I can write a patch

**Comment by dm1tz** [comment]
> Can you send me the content of sigchld?, I can write a patch

Also reproducible with synced [autostart patch](https://github.com/djpohly/dwl/compare/main...dm1tz:04rc1-autostart.patch) , adding `!xwayland ||` before `in.si_pid` as in #345 doesn't help.

**Comment by fauxmight** [comment]
@sevz17: The patch sought is probably a proper update of your autostart branch. I began working on this keeping the `sigchld` function where it is in 0.4-rc1 but got bogged down in the function's logic trying to three-way reconcile the differences between the old autostart, the pre 0.4-rc1 `sigchld` and the 0.4-rc1 `sigchld` (and then the new changes from 16a49e9).

Perhaps your more familiar eyes on the autostart branch could make this merge correctly.

**Comment by sevz17** [comment]
> @sevz17: The patch sought is probably a proper update of your autostart branch. I began working on this keeping the `sigchld` function where it is in 0.4-rc1 but got bogged down in the function's logic trying to three-way reconcile the differences between the old autostart, the pre 0.4-rc1 `sigchld` and the 0.4-rc1 `sigchld` (and then the new changes from [16a49e9](https://github.com/djpohly/dwl/commit/16a49e99557563252b9f91db767b431e2238f587)).
> 
> Perhaps your more familiar eyes on the autostart branch could make this merge correctly.

I see... tomorrow I'll update all my patches.

**Comment by sevz17** [comment]
> I see... tomorrow I'll update all my patches.

Done.
