### ISSUE TITLE
Freeze when spawing floating window in tiling layout

### ISSUE THREAD

**Issue by maxagabb** [djpohly/dwl#349]
## Info
dwl version: HEAD 16a49e99557563252b9f91db767b431e2238f587
wlroots version: 0.16
## Description
Hello! dwl freezes for me when spawning a floating window inside tiling layout. Seems to freeze longer if there are multiple tiled windows. Also freezes if I try to resize it. 

For example launching alacritty like so:
`setsid -f alacritty --class float`
```
static const Rule rules[] = {
	/* app_id     title       tags mask     isfloating   monitor */
	{ "float",    NULL,       0,            1,           -1 },
	{ "firefox",  NULL,       1 << 8,       0,           -1 },
};
```
 **EDIT:** Issue seems to be specific to alacritty

**Comment by sevz17** [comment]
Probably it was introduced by 017bb7d7521f68d37bfe656c10f45edbcc92dd61, can you revert it and test?

**Comment by maxagabb** [comment]
Yup, that fixes the issue completely

**Comment by sevz17** [comment]
It wasn't a freeze for me, the only thing I noticed is that I couldn't move the mouse, key presses seemed fine.

**Comment by maxagabb** [comment]
Just tried this again with `exec dwl` (no startup script). Also I have two monitors.

Issue did not happen with foot terminal, but I saw a freeze when resizing alacritty after launching it as floating.

I'm using alacritty-sixel-git from the AUR so that could be an issue.

**Comment by maxagabb** [comment]
Tried this again with alacritty from normal repo and dwl without startup script.

Issue happens when there are multiple tiled alacritty windows. Keyboard input seems to work (I can close windows to get back the mouse)

**Comment by maxagabb** [comment]
Now I feel this not a dwl bug since foot works fine. It's probably some issue in alacritty-wlroots that can be replicated with https://github.com/djpohly/dwl/commit/017bb7d7521f68d37bfe656c10f45edbcc92dd61

Should I close this?

**Comment by sevz17** [comment]
Testing again I discovered that the cursor is perfectly functional, for some reason alacritty (or dwl?, time ago I did a commit related to it) hide it, foot doesn't.

**Comment by Job79** [comment]
I am also experiencing "freezes" after the latest updates. It is pretty simple to reproduce:
1. Open 2 chromium or alacritty windows on a tag (doesn't seem to work when using foot)
2. Switch to another tag and open some other applications
3. Go bag to the tag with chromium/alacritty

It seems to freeze 9/10 times, switching focus between the windows using alt+j/k or the mouse seems to resolve the freeze. 
Not sure if this is the same issue, but it seems related. Note that I am using the wlroots-next branch with wlroots git so there is a small chance that it is a wlroots problem.

**Comment by Job79** [comment]
Just reverted https://github.com/djpohly/dwl/commit/017bb7d7521f68d37bfe656c10f45edbcc92dd61 locally and now it works fine, so this is definitely a dwl problem. A shame because I really liked that the flickering problem was resolved.

**Comment by sevz17** [comment]
I reverted the commits, this can be closed.
