### ISSUE TITLE
Problems (solved) compiling v0.4-rc2 + wlroots-0.16 on Archlinux

### ISSUE THREAD

**Issue by antoniocorbi** [djpohly/dwl#352]
## Info
dwl version: v0.4-rc2
wlroots version: 0.16
## Description

As the title says I have had problems compiling Dwl v0.4-rc2 + wlroots-0.16 on Archlinux.
They are now solved, but I had to make two changes to Dwl's Makefile. 

These are:
1. Remove the flag `-pedantic` from DWLDEVCFLAGS because wlroots gave problems with an union declared without name.
2. In order to find the header "pixman.h" I had to add "pixman-1" to the list of PKGS in:
    `PKGS      =  wayland-server xkbcommon libinput pixman-1 $(XLIBS)`
 
With these two changes now I have Dwl working as expected, of course using the LD_PRELOAD trick to load my local wlroots-0.16 as Archlinux still provides wlroots-0.15.

**Comment by sevz17** [comment]
> 1. Remove the flag `-pedantic` from DWLDEVCFLAGS because wlroots gave problems with an union declared without name.

even if `-pedantic` is present, it shouldn't cause problems because `-Werror` is not present in our flags

> 2. In order to find the header "pixman.h" I had to add "pixman-1" to the list of PKGS in:
    `PKGS      =  wayland-server xkbcommon libinput pixman-1 $(XLIBS)`

```
$ pkg-config --cflags wlroots
-I/usr/lib64/libffi/include -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/elogind 
```
