### ISSUE TITLE
dwl-0.4-rc2 crashes when playing any video in firefox

### ISSUE THREAD

**Issue by ephemer4l** [djpohly/dwl#356]
## Info
dwl version: 0.4-rc2
wlroots version: 0.16
## Description
I've finally upgraded to 0.4 but now I can't play videos in firefox anymore. dwl crashes as soon as the video starts playing. Downloaded videos played with MPV pose no issue. Please advise me on what logs to share.

**Comment by sevz17** [comment]
Please send me the backtrace.

**Comment by ephemer4l** [comment]
@sevz17 I'm glad to say that this magically disappeared. I think I might have been installing rc1 thinking that it was rc2.
