### ISSUE TITLE
Shortcut with shift key not working on us-intl keymap

### ISSUE THREAD

**Issue by a-denoyelle** [djpohly/dwl#371]
## Info
dwl version: 0.4
wlroots version: 0.16.1

## Description
Hello,

First, thank you for providing a promising alternative for dwm on wayland !

I'm using us-intl keyboard keymap variant. This is done by specifying the following environment variables before starting dwl : 
```
export XKB_DEFAULT_LAYOUT=us
export XKB_DEFAULT_VARIANT=intl
```

I have an issue with a specific shortcut combination : `MODKEY + WLR_MODIFIER_SHIFT + XKB_KEY_6`. This shortcut does nothing which prevents me to tag a window for the 6th desktop. This is the only one I have an issue. It is probably because  "ASCII circum" is a dead key on this keymap : I have to double press the key to type it. FYI, all other shortcuts with shift key function properly, most probably because they are not combine with a dead key.

**Comment by n1rdeks** [comment]
maybe need add to config.h?
for example, my custom layouts (improved Dvorak):
```
static const struct xkb_rule_names xkb_rules = {
    /* can specify fields: rules, model, layout, variant, options */
    .layout = "us,ru",
    .variant = "inkl,inklru",
    .options = "grp:alt_shift_toggle",
};
```
All work fine.

And watch here:
```
  TAGKEYS(          XKB_KEY_1, XKB_KEY_!,                           0),
```
XKB_KEY_1 - first key without Shift modificator
XKB_KEY_! - with Shift

**Comment by PalanixYT** [comment]
just change it to ```XKB_KEY_dead_circumflex```

**Comment by a-denoyelle** [comment]
> just change it to `XKB_KEY_dead_circumflex`

Thanks it works perfectly as expected. I close this issue.
