### ISSUE TITLE
input: touchpad and external mouse.

### ISSUE THREAD

**Issue by n1rdeks** [djpohly/dwl#372]
## Info
dwl version: git (2023, 14)

## Description
If I use ```static const int natural_scrolling = 1;```, my external USB mouse change scrolling too.

In other WM input separated.

**Comment by bencollerson** [comment]
You probably need to add some logic to dwl.c:createpointer() so that natural_scrolling is only enabled on devices that you want it enabled on.

**Comment by bencollerson** [comment]
Maybe something like this patch: https://github.com/djpohly/dwl/compare/main...bencollerson:dwl:pointer-rules.patch

I haven't properly tested it. But it might help.

**Comment by n1rdeks** [comment]
thanks for fast answer and patch. In my config not work... IMO, name of device, maybe I choose wrong - ```libinput list-devices```. 

My config for debug:
[config.txt](https://github.com/djpohly/dwl/files/10430678/config.txt)

**Comment by n1rdeks** [comment]
oh... Sorry, night. All work fine. I use in RiverWM this ~~hack~~ lib - https://gitlab.com/warningnonpotablewater/libinput-config/

I disable and all fine. Thanks. As u see, my eng is terrible. But need write little docs ;) Cheers.
