### ISSUE TITLE
Keys not work on another layout

### ISSUE THREAD

**Issue by n1rdeks** [djpohly/dwl#379]
## Info
dwl version: 0.4 (git)
wlroots version: latest 

If I change layout, all keys with LOGO/ALT not work.
Need add keycode or some mechanism. 

P.S. SwayWM and RiverWM have a solution and options in config.

**Comment by krypciak** [comment]
What do you mean by a layout? A keyboard layout? Tiling layout (floating, monocle, etc.)?
By `all keys` you mean keybindings?
Can tell us more about the solution used in Sway/River?

**Comment by n1rdeks** [comment]
'ru', 'es', 'fra' etc... Language (not 'us'). Need some univesal keycodes for keys. Or in another Layout u dont change a workspace.

**Comment by n1rdeks** [comment]
> Can tell us more about the solution used in Sway/River?

```bindsym --to-code``` in Sway

Freud in RiverWM create hack... Here: https://github.com/riverwm/river/pull/753

**Comment by krypciak** [comment]
I have made a hack that switches the keyboard layout to qwerty us when a mod key is pressed (except shift). After it's released, it goes back to the previous layout.
You can also set a keybining to switch the layout. Would you like a patch for that?

**Comment by n1rdeks** [comment]
nope... I dont use copy/paste in keys ;). I use select/middle button of mouse.
I use patched version of xkb (I create personal layout for programming). 

And my accords or macros did not work (I think).

So, I think, need complex solution of any languages and custom keybindings. All people different.

**Comment by krypciak** [comment]
Any keyboard layout with any language would work. It doesn't matter that you have a custom keyboard layout.
Example:
```
Your default keyboard layout is dvorak
Press CTRL, keyboard layout changes to qwerty (or any of your choise)
Press F, The client goes fullscreen
Release F and CTRL
Keyboard layout goes back to dvorak (or any of your choise)
```
In this case only 1 keybinding definition is needed, and will work for all layouts.

That workes for me, and I don't see any reson why it wouldn't work for you.

**Comment by n1rdeks** [comment]
))) Why not? Let's try )) But... my CTRL in another place ;) I use Emacs and I crack my HHKB to 40% keyboard with layers (hello, 'Neo' - https://neo-layout.org). So... All my keys changed. ALT, CAPS, ESC, CTRL, LOGO(WIN) - all this keys are rebinding.

**Comment by krypciak** [comment]
What the hell. Is very much possible to do this. You would first need to pick a keyboard layout and write our keybindings for it. What keyboard layouts do you use? How different are they form each other?

**Comment by n1rdeks** [comment]
> How different are they form each other?

Yep ;))) Totally different. For example, this ver 0.001. Later I change all special keys and some layers...
![version1-0](https://user-images.githubusercontent.com/63796667/214809884-3c60ed75-c10e-47b9-971f-61823029fb5a.jpg)

**Comment by krypciak** [comment]
Is this the only keyboard layout you use?

**Comment by n1rdeks** [comment]
US, RU.

**Comment by krypciak** [comment]
Alright, so I assume that both layouts you use share the same mod key placements. All you need to do is make keybindings that work for the US layout,
and I'll prepare a patch that allows you to switch between the layouts and keep the US keybindings for a RU layout.

**Comment by n1rdeks** [comment]
>Alright, so I assume that both layouts you use share the same mod key placements. All you need to do is make keybindings that work for the US layout,
and I'll prepare a patch that allows you to switch between the layouts and keep the US keybindings for a RU layout.

Ohoh... Sorry for that, but... If DWL later change DWM - u take a fat user base (DB). And maybe need fix this on keycodes, not listen symbols? 
This is my config of keyboard
[inkl.tar.gz](https://github.com/djpohly/dwl/files/10508251/inkl.tar.gz)

**Comment by krypciak** [comment]
Actually, I'm dumb. Take a look at this patch: https://github.com/djpohly/dwl/wiki/keycodes.
It might just do what you want all along.

**Comment by n1rdeks** [comment]
holy!.. Wow, thanks. Actually - 'dumb' - its me. I use 3 patches and not see this... Crap. Thanks, after testing I close this issue.

**Comment by n1rdeks** [comment]
Ah, and my Eng is terrible, so please, add link on this patch (or say to merge this patch in master branch in Discord) in README, Wiki (key section) or somewhere in documentation.

**Comment by sevz17** [comment]
> I try patch https://github.com/djpohly/dwl/wiki/keycodes. Not working properly. In keys.h codes added only for QWERTY layout. In Dvorak all keys are drop. (or need rewrite keys.h, but how to be in Colemac or another layout?)

`keys.h` is only a helper, even if you use another layout (and/or variant), you can use it as reference for your keybindings.

> IMO, need something for all keymaps (maybe use xkb, without any external hacks?)

I just updated the patch, I included the program I used to generate `keys.h`
