### ISSUE TITLE
add comment with choise buttons (ALT or Super key), analog Dmenu (bemenu)

### ISSUE THREAD

**Issue by n1rdeks** [djpohly/dwl#38]
// in here
#define MODKEY WLR_MODIFIER_ALT

with super-key (LOGO?) -  segmentation fault.

not working any 'menu' - bemenu not work.
need add this option to config.h

**Comment by ivan-krukov** [comment]
I think the key names that you are looking for are defined here: [https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_keyboard.h]()

```
#define MODKEY WLR_MODIFIER_LOGO
```

Presently, the config only has the binding to open a terminal (`MOD+Shift+Ret`) - you'd have to set up `bemenu` and the like yourself.


Building from the latest branch worked for me.

**Comment by n1rdeks** [comment]
Thanks for reply. Well, i try again work with DWL and Wayland. 

P.S. Однако неплохо бы повторить немца с его DWM до конца. Может, я докину патчей, если переползу на wayland с X11. 

Best regards
