### ISSUE TITLE
PATCH - keychord implementation for flexible key sequences

### ISSUE THREAD

**Issue by yveszoundi** [djpohly/dwl#385]
### Info

- dwl's commit: [f8373cc](https://github.com/djpohly/dwl/commit/f8373ccf2581fa481602bbb7528ba8871f6d5c85) (`0.4` main branch as of `2023-02-14`)
- wlroots version: 0.16 (Void Linux default package)
- [patch contents](https://github.com/djpohly/dwl/compare/main...yveszoundi:dwl:v0.4-keychord-2023-02-14.patch)

### Description

A patch that lets users map a sequence of keys instead of a singular keystroke.

- This is based on the [dwm keychord patch](https://dwm.suckless.org/patches/keychord/) 
- This includes the [keycodes patch](https://github.com/djpohly/dwl/wiki/keycodes)
- This brings more flexibility to users of the [chainkeys patch](https://github.com/djpohly/dwl/wiki/chainkeys)
  - You can implement more closely [stumpwm](https://stumpwm.github.io/) style of keybindings with a "prefix key" (`Ctrl-t`)
  - You can use additional modifiers after the "chainkey" or not (`Alt-x uo` would work fine)
  - You're not limited to default simple sequences (limit of `5` in the `Keychord` struct)
- This can help mitigate keyboard shortcuts conflicts in virtual machines (host vs "VM runner" vs guest): Imagine a workflow with `emacs` inside a `tmux` session from a virtual machine, and constantly hitting the "wrong keys"

### Example

In the minimal example below, the original `Alt-p` binding becomes `Ctrl-t Ctrl-o`.

- `PREFIXKEY` is set to `t`
- `MODKEY` is set to `Ctrl`, `MOD_CONTROL` is mentioned explictly to emphasize that it could be a different modifier

```C
static const Key keys[] = {
	/* Note that Shift changes certain key codes: c -> C, 2 -> at, etc. */
	/* modifier                  key              function  argument */
	{ MODKEY,                    XKB_KEY_p,       spawn,    {.v = menucmd} }
};
```
becomes

```C
static const Keychord keychords[] = {
  /* Note that Shift changes certain key codes: c -> C, 2 -> at, etc. */
  /* count key_sequences                          function  argument */
  { 2, {{MODKEY, PREFIXKEY}, {MOD_CONTROL, Key_o}},  spawn,    { .v = menucmd } }
};
```

**Comment by yveszoundi** [comment]
I hope that it's the right process for patch consideration in the wiki. Please note that I don't really know/use C, but this seems to work well for me, any feedback or comments are appreciated.

**Comment by sevz17** [comment]
> I hope that it's the right process for patch consideration in the wiki.

Actually you don't need to ask our permission to post a patch. You only need to follow [these](https://github.com/djpohly/dwl/wiki/Patches#submitting-patches) instructions.

**Comment by yveszoundi** [comment]
Thank you, I made the relevant wiki edits.
