### ISSUE TITLE
Count of clients should be visible when on monocle layout

### ISSUE THREAD

**Issue by pm4rcin** [djpohly/dwl#387]
Hi, in DWM the count of clients on given tag is visible when on monocle and there's more than 1 window. Since we want to achieve parity it should be implemented. Also if I recall correctly for  >9 it's `9+`.

**Comment by yveszoundi** [comment]
I implemented the feature as it exists in `dwm`:
- The client count is displayed when greater than zero for the monocle layout
- @pm4rcin, per latest `dwm` code, the client count is displayed "as is" even when greater than 9

This has been tested with [somebar](https://sr.ht/~raphi/somebar/) and [dwlb](https://github.com/kolunmi/dwlb) as status bars, and I assume that it works pretty much the same with [yambar](https://codeberg.org/dnkl/yambar) , [waybar](https://github.com/Alexays/Waybar) or any other bars that support `dwl`.
