### ISSUE TITLE
invalid key combination

### ISSUE THREAD

**Issue by gan-of-culture** [djpohly/dwl#392]
## Info
dwl version: 0.4
wlroots version: 0.16.2-1
## Description

When I switch the KEYMAPPING from this:
```
{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_less,       tagmon,         {.i = WLR_DIRECTION_LEFT} },
{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_greater,    tagmon,         {.i = WLR_DIRECTION_RIGHT} },
```
to this:
```
{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_comma,         tagmon,         {.i = WLR_DIRECTION_LEFT} },
{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_period,        tagmon,         {.i = WLR_DIRECTION_RIGHT} },
```
both key combinations will output either `:` or `;` and not run the function `tagmon`. All the other `MODKEY + WLR_MODIFIER_SHIFT` work for me.

**Comment by sevz17** [comment]
From config.def.h:
> /* Note that Shift changes certain key codes: c -> C, 2 -> at, etc. */

You can get the correct keysym using [wev](https://git.sr.ht/~sircmpwn/wev), or depending on your distro you could use `xkbcli interactive-wayland` (on gentoo it is installed if libxkbcommon is compiled with USE=tools)
