### ISSUE TITLE
moving windows not working with swiss-german keymap

### ISSUE THREAD

**Issue by jjjt-git** [djpohly/dwl#396]
## Info
dwl version: 0.4
wlroots version: 0.16.1
MODKEY was changed to Super (WLR_MODIFIER_LOGO)
swiss-german key layout
no other changes made to config
## Description
When trying to move windows to another tag or monitor, it does not work as expected.
For a foot-window (moved from tag 1 to x but result was y):
x | y
1 | '+' entered
2 | '"' entered (double quotes)
3 | moved to tag 8
4 | 'ç' entered
5 | moved to 5
6 | moved to 7
7 | '/' entered
8 | moved to 9
9 | moved to all tags
when moving to another monitor, ';' or ':' are entered

when using the default keymap, it works

**Comment by PalanixYT** [comment]
Not a bug, just change the keybinds in config.h

**Comment by jjjt-git** [comment]
Thanks for the notice. Now it works.
