### ISSUE TITLE
Remove move-stack-top patch?

### ISSUE THREAD

**Issue by 0undefined** [djpohly/dwl#400]
Hi,
I've recently added the [move-stack-top](https://github.com/djpohly/dwl/wiki/move-stack-top) patch to the patches section on the wiki,
however I am uncertain whether it even fits the list as a possible patch, since it is just an extension of sam-barrs [movestack](https://github.com/djpohly/dwl/wiki/movestack) patch.
Should it be removed or is it fine?
Should I try to contact the original patch author to suggest adding my edit to his patch?

Any input on this matter is much appreciated.

**Comment by PalanixYT** [comment]
You can reach out to the original author but I wouldn't remove the patch
