### ISSUE TITLE
Wrong include path for xwayland

### ISSUE THREAD

**Issue by macarona-salsa** [djpohly/dwl#404]
## Info
dwl version: v0.4
wlroots version: 0.16.1
## Description
When building dwl with the XWAYLAND macro turned on in config.mk, I get the following output:
```
c99  `pkg-config --cflags wlroots wayland-server xkbcommon libinput xcb xcb-icccm` -I. -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809L -DVERSION=\"`git describe --tags --dirty 2>/dev/null || echo 0.4`\" -DXWAYLAND -pedantic -Wall -Wextra -Wdeclaration-after-statement -Wno-unused-parameter -Wno-sign-compare -Wshadow -Wunused-macros -Werror=strict-prototypes -Werror=implicit -Werror=return-type -Werror=incompatible-pointer-types -O1 -c dwl.c
dwl.c:56:10: fatal error: wlr/xwayland.h: No such file or directory
   56 | #include <wlr/xwayland.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:60: dwl.o] Error 1
```
When I look in my `/usr/include/wlr` I find that there's no `xwayland.h`, but instead a directory `xwayland` containing `server.h xwayland.h`. I tried changing the #include lines in dwl.c to correct the include path but that gave me linker errors.

Tested on tag v0.4 and commit bbdf2a913b72e7a308ee0dfde6518a4285d4a775.
Steps to reproduce:
1. uncomment the XWAYLAND and XLIBS variables in config.mk

```
diff --git a/config.mk b/config.mk
index f50156f..a20a8f0 100644
--- a/config.mk
+++ b/config.mk
@@ -10,5 +10,5 @@ MANDIR = $(PREFIX)/share/man
 XWAYLAND =
 XLIBS =
 # Uncomment to build XWayland support
-#XWAYLAND = -DXWAYLAND
-#XLIBS = xcb xcb-icccm
+XWAYLAND = -DXWAYLAND
+XLIBS = xcb xcb-icccm
```
2. run `make`

Thank you.

**Comment by fauxmight** [comment]
@macarona-salsa: Check your distro's packaging of wlroots. Or blindly reinstall and see if the `/usr/include/wlr/xwayland.h` header shows back up.

The header at `/usr/include/wlr/xwayland/xwayland.h` is *not* the same as the one at `/usr/include/wlr/xwayland.h`

**Comment by macarona-salsa** [comment]
Thanks a lot. It was that.
I'm on gentoo and didn't know I needed the X use flag turned on for wlroots. I installed again and now I have /usr/include/wlr/xwayland.h. 🙏

**Comment by fauxmight** [comment]
Glad it was a straight-forward resolve.
Please feel free to close the issue.
