### ISSUE TITLE
printstatus() systemd journal flood.

### ISSUE THREAD

**Issue by s-sergiu** [djpohly/dwl#405]
When I run dwl as a systemd service the printstatus function prints and floods the journalctl logs. 
For a normal user usage is it necessary to make use of the function and continuously print in the background?
Can it run without any issues if you don't call the printstatus function every time in different other functions?

Apart from that I really enjoyed dwm  when I was using X and I want to thank you for creating a wayland version of it.

**Comment by bencollerson** [comment]
Couldn't you set up the systemd service to redirect the output to /dev/null? Something like:

StandardOutput=null

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=

The prirtstatus() command is important for communication to status bars etc.

**Comment by PalanixYT** [comment]
You could try `dwl -s <&-`

**Comment by s-sergiu** [comment]
> Couldn't you set up the systemd service to redirect the output to /dev/null? Something like:
> 
> StandardOutput=null
> 
> https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=
> 
> The prirtstatus() command is important for communication to status bars etc.

Thank you, I will use this.
