### ISSUE TITLE
Multiple windows showed as focused if a popup window isn't closed before moving cursor to other windows with sloppyfocus

### ISSUE THREAD

**Issue by BenJarg** [djpohly/dwl#408]
## Info
dwl version: commit bbdf2a9
wlroots version: 0.16.2

## Description
This is with sloppyfocus = 1, specifically. For example, if using gPodder in tiling mode with other windows, I open the one of the drop-down menus from the top. Before closing it the menu, I move the cursor over other windows. The other windows the cursor move over have highlighted borders to show they're focused, even though the focus is still on gPodder with the drop-down menu. Typing doesn't interact with these other highlighted, only gPodder, until I click one of the other windows and it fixes things. The drop down menu is destroyed when I click one of these other windows.

**Comment by sevz17** [comment]
@BenJarg, does #409 fix this?

**Comment by BenJarg** [comment]
@sevz17 Yes, it does

**Comment by sevz17** [comment]
Thanks for testing!
