### ISSUE TITLE
Popups can go offscreen

### ISSUE THREAD

**Issue by godalming123** [djpohly/dwl#413]
## Info
dwl version: latest
wlroots version: 0.16.X
## Description
For example in firefox when you open the right click menu with your cursor at the bottom of the screen the subsurface isn't fully on the screen

**Comment by sevz17** [comment]
> For example in firefox when you open the right click menu with your cursor at the bottom of the screen the subsurface isn't fully on the screen

Thats pretty weird, I think you are referring to popups, in that case we cannot do anything because we should have handled that.
https://github.com/djpohly/dwl/blob/0729f18dce85cb79b8aaac325a43dba0c5e96ab3/dwl.c#L990-L1003

Did you do something else, like moving the client to another monitor?

**Comment by godalming123** [comment]
Thinking about it, it is possible that firefox was running with xwayland but otherwise I thought that the right click menu was a Wayland subsurface and to your comment on not being able to fix it, this does not happen in hyprland or gnome.

**Comment by sevz17** [comment]
> Thinking about it, it is possible that firefox was running with xwayland but otherwise I thought that the right click menu was a Wayland subsurface

It shouldn't matter, I remember that time ago running firefox with xwayland made the popups behave better than running natively in wayland :)

> and to your comment on not being able to fix it, this does not happen in hyprland or gnome.

Actually this is pretty strange, I don't know why but popups works perfectly to me in a clean build of dwl, can you try to reproduce it while running dwl inside another compositor?

**Comment by godalming123** [comment]
Wierd, I am unable to reproduce after rebuilding DWL
