### ISSUE TITLE
stdout broken when option '-s' is used

### ISSUE THREAD

**Issue by leg7** [djpohly/dwl#414]
## Info
dwl version: [797e0c7](https://github.com/djpohly/dwl/commit/797e0c74b2cbf4a49f83c9269abec06f3293d00c)
wlroots version: 0.16.2-1
## Description
When I start dwl with the -s option stdout gets blocked and won't update even if I block stdin from the -s arguments.

```
dwl -s 'exec <&-; exec >&-; eww-launch & setbg -i & foot --server & ydotool & fnott & wlsunset -t 3000 -d 0 -s 20:00 -S 06:00 &' > tmp
```

I've tried all kinds of ways to block stdin and stdout with <&- but it always results in stdout not updating. Here's how tmp looks like:

```
eDP-1 title 
eDP-1 appid 
eDP-1 fullscreen 
eDP-1 floating 
eDP-1 selmon 0
eDP-1 tags 0 1 0 0
eDP-1 layout 
DP-5 title 
DP-5 appid 
DP-5 fullscreen 
DP-5 floating 
DP-5 selmon 0
DP-5 tags 0 1 0 0
DP-5 layout 
eDP-1 title 
eDP-1 appid 
eDP-1 fullscreen 
eDP-1 floating 
eDP-1 selmon 0
eDP-1 tags 0 1 0 0
eDP-1 layout []=
```

It just stays like this if I call anything with -s

**Comment by dimkr** [comment]
`dwl -s 'sh -c "exec <&-; exec >&-; eww-launch & setbg -i & foot --server & ydotool & fnott & wlsunset -t 3000 -d 0 -s 20:00 -S 06:00 &'" > /dev/null`

**Comment by leg7** [comment]
I would like to have `dwl` stdout work correctly and not get blocked by the `-s` option so that I can use the tag information in my status bar.

**Comment by bencollerson** [comment]
If you want to run different processes from -s and have them each handle the dwl output differently, you could try using pee (pipe tee) from moreutils: https://joeyh.name/code/moreutils/

This allows you to start utilities in some init script that closes off stdin, while status bars have their own input from dwl.

eg:

dwl -s 'pee somebar initstuff some-other-script'

**Comment by leg7** [comment]
So there is no way to have startup programs with dwl without using external programs?

For example even if I do ```dwl -s 'foot --server <&-' > tmp``` like in the README dwl will not update tmp with tag information, it's just going to get blocked.

**Comment by bencollerson** [comment]
Yes dwl can only start a single startup program. It sends output to that program instead of stdout, even if you close the stdin of the startup program. You could patch your dwl to accept a list of startup programs, but using `pee` to spawn off multiple child processes is simpler.

**Comment by leg7** [comment]
Ok thank you
