### ISSUE TITLE
Adaptive Sync Support

### ISSUE THREAD

**Issue by MilesBreslin** [djpohly/dwl#42]
wl-roots now has adaptive sync support built-in. `wlr_output_enable_adaptive_sync`, documented [here](https://github.com/swaywm/wlroots/blob/79e03c7d456adaaa1b408b8c48a05ac051388770/include/wlr/types/wlr_output.h#L270-L279), should enable this.

**Comment by djpohly** [comment]
Sounds like an easy add.  Submit a PR?

**Comment by djpohly** [comment]
Merged from commit 444a5f9.
