### ISSUE TITLE
dwl does not allow xwayland clients to change override_redirect flag

### ISSUE THREAD

**Issue by StratusFearMe21** [djpohly/dwl#432]
## Info
dwl version: HEAD:wlroots-next (24a337e)
wlroots version: HEAD (05dd08af)
## Description
It appears that Xwayland is no longer able to reason whether a pop-up window is an actual window or not, and will focus/unfocus the window as if it were an actual window. This seems to cheese REAPER's logic somehow (at least that's what it looks like to me). This is a video of what's happening (with expanded boarder size to illustrate the problem), first I tried to access the context menu with normal mouse settings, then I tried it with `mouse-follows-focus` turned on 

https://github.com/djpohly/dwl/assets/57533634/1b3d47e9-1a9e-4f5c-9ce7-3dd846e522b6

**Comment by StratusFearMe21** [comment]
P.S I was able to reproduce this on the main line with all my mods and patches stripped

**Comment by sevz17** [comment]
Where can I find the source code/binaries of the client?

**Comment by StratusFearMe21** [comment]
For REAPER? You can find downloads on https://reaper.fm, or you can install the Arch package `reaper`

**Comment by sevz17** [comment]
This is troublesome, seems like reaper creates popups with the [override redirect flag](https://x.org/releases/current/doc/libX11/libX11/libX11.html#Override_Redirect_Flag) turned off, and then turn it on.

**Comment by Twinkie001** [comment]
I don't know it it's any help, but Sway doesn't seem to have any problems with the flag and it's also written in C...
Reaper seems to work flawlessly on Sway, especially the git version. Maybe there could be some clues in their source code  to solving this...?

**Comment by StratusFearMe21** [comment]
REAPER also seems to work in Hyprland

**Comment by Twinkie001** [comment]
Yeah, with a couple of window rules added... If stock in it makes plugins and sends disappear if you move the mouse away from the plugin popup.

**Comment by Twinkie001** [comment]
Here is the Sway issue about this. Looks like they removed something from their xwayland.c file.
https://github.com/swaywm/sway/issues/6324
There's a whole bunch of info in there, don't know if any of it applicable to dwl but maybe some basic wayland stuff can hold some clues to solving this.

**Comment by sevz17** [comment]
@StratusFearMe21 @Twinkie001, reaper now works on the wlroots-branch (https://codeberg.org/dwl/dwl/src/branch/wlroots-next)

Twinkie001 thank you very much for trying to give solutions. :)
StratusFearMe21 thanks for reporting.

**Comment by StratusFearMe21** [comment]
> @StratusFearMe21 @Twinkie001, reaper now works on the wlroots-branch (https://codeberg.org/dwl/dwl/src/branch/wlroots-next)
> 
> Twinkie001 thank you very much for trying to give solutions. :) StratusFearMe21 thanks for reporting.

Thank you! Can confirm that whatever you did worked!
