### ISSUE TITLE
kvm, qxl: Libinput can not be found on xf86-video-qxl-0.1.5-6/xf86-video-qxl-0.1.5-r6

### ISSUE THREAD

**Issue by matu3ba** [djpohly/dwl#45]
Interestingly does sway work for me without problems on Alpine Linux.

The error log (without disabling libinput on WLR_LIBINPUT_NO_DEVICES=1 and completely breaking the system) is:

pci id for fd 9: 1b36:0100, driver (null)
MESA-LOADER: failed to open qxl (search paths /usr/lib/xorg/modules/dri)
failed to load driver: qxl
00:00:01.133 [ERROR] [backend/libinput/backend.c:84] libinput initialization failed, no input devices
00:00:01.133 [ERROR] [backend/libinput/backend.c:85] Set WLR_LIBINPUT_NO_DEVICES=1 to suppress this check
00:00:01.133 [ERROR] [backend/multi/backend.c:32] Failed to initialize backend.
startup: backend_start: Not a tty

Development on xf86-video-qxl-0.1.5-6 looks to be [stopped 1 year ago](https://gitlab.freedesktop.org/xorg/driver/xf86-video-qxl).
This user had the [same problem](https://bbs.archlinux.org/viewtopic.php?id=242038).
Are there alternatives without qxl like [these](https://wiki.archlinux.org/index.php/QEMU/Guest_graphics_acceleration) or should I file this bug also at wlroots?

**Comment by djpohly** [comment]
Looks like QXL does not provide a DRI driver (it would be `qxl_dri.so`) for Mesa - nothing that either dwl or wlroots can do about that.  Maybe try the std or virtio driver for QEMU instead?
