### ISSUE TITLE
Can't get pipewire to work

### ISSUE THREAD

**Issue by jan-sopi** [djpohly/dwl#450]
can't get pipewire to work with the error `Failed to connect to session bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`
dwl version: 0.4
wlroots version: 0.16.2-1
I've tried launching dwm with pipewire using the -s switch, but it didn't work. I'm new to wayland and dwl so i'm not sure how to launch it when I boot. either way with or without it it always results in the same error
```
[E][04433.224356] mod.rt       | [     module-rt.c:  236 pw_rtkit_bus_get()] Failed to connect to session bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
[W][04433.225418] mod.rt       | [     module-rt.c:  272 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][04433.225629] mod.rt       | [     module-rt.c:  272 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[W][04433.225717] mod.rt       | [     module-rt.c:  654 set_nice()] could not set nice-level to -11: No such file or directory
[W][04433.225863] mod.rt       | [     module-rt.c:  272 translate_error()] RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
[E][04433.226106] mod.protocol-native | [module-protocol-:  712 lock_socket()] server 0x562417b0ea00: unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
[E][04433.226164] pw.conf      | [          conf.c:  574 load_module()] 0x562417ace510: could not load mandatory module "libpipewire-module-protocol-native": Resource temporarily unavailable
[E][04433.226348] default      | [      pipewire.c:  105 main()] failed to create context: Resource temporarily unavailable
```

**Comment by PalanixYT** [comment]
Try `dbus-launch dwl`

**Comment by DarioTD** [comment]
It works for me however I do execute `dbus-run-session dwl`
I use pipewire + wireplumber

**Comment by PalanixYT** [comment]
I personally start a global dbus session so that I can use pipewire in the tty.
`dbus-run-session` starts a new session and `dbus-launch` starts it inside an old session. So yes, mb

**Comment by dimkr** [comment]
I use `dbus-run-session -- dwl ~/.dwlinitrc`, with this in ~/.dwlinitrc:

```
#!/bin/sh

pipewire > /dev/null 2>&1 &

(
     while [ ! -e $XDG_RUNTIME_DIR/pipewire-0 ]; do sleep 0.1; done
     pipewire-pulse > /dev/null 2>&1 &
     wireplumber > /dev/null 2>&1 &
) &

export PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native
export PULSE_COOKIE=$XDG_CONFIG_HOME/pulse/cookie

dbus-update-activation-environment WAYLAND_DISPLAY DISPLAY PULSE_SERVER PULSE_COOKIE
```

**Comment by sevz17** [comment]
You need a D-Bus session to start pipewire/wireplumber, you can run either `dbus-launch --exit-with-session dwl -s /path/to/your/script` or `dbus-run-session dwl -s /path/to/your/script`

and your script can be pretty similar to what gentoo [does](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/pipewire/files/gentoo-pipewire-launcher.in).
