### ISSUE TITLE
Alacritty windows not closing after exiting from shell

### ISSUE THREAD

**Issue by BenJarg** [djpohly/dwl#456]
## Info
dwl version: fbd84ac
wlroots version: 0.16.2
## Description
This is introduced by fbd84ac. Prior to this commit, exiting from the shell in alacritty with `exit` or ctr-d will close the alacritty window, which is the expected behavior. With this commit, now alacritty windows will echo "exit" upon closing the shell, but the window remains, not closing. It won't close until running `killclient` manually. I assume it's not an alacritty bug, since it arose only after this commit, but it could also be an alacritty issue possibly.

**Comment by fauxmight** [comment]
I experience this behavior as well.
In addition, I note that htop (in a new terminal) shows a still-running-but-should-have-exited alacritty terminal consumes excessive CPU (88-94%) and that system temperature rises commensurately until the should-be-dead terminal is force killed.

**Comment by fauxmight** [comment]
This issue may be closable: When building dwl clean without patches, alacritty closes cleanly and correctly as expected. Testing with one patch at a time to determine the responsible entity.

**Comment by BenJarg** [comment]
I still have this issue when on main, with no patches. One noteworthy thing to mention is that the alacritty window will only have this issue if it's a direct child of dwl, i.e. only if started from a dwl keybinding. If started by another window of alacritty, for example, it will close normally when the shell exits.

**Comment by sevz17** [comment]
@BenJarg, @fauxmight can you test #460

**Comment by BenJarg** [comment]
That fixes it

**Comment by fauxmight** [comment]
Resolved here, too.
