### ISSUE TITLE
colors

### ISSUE THREAD

**Issue by apprehensions** [djpohly/dwl#466]
I've noticed that many users face issues simply with colors, as no examples are provided for hex colors, no converters, and many of them get lost.

what i propose is either:

1. to document this and explain a method to convert it, using the [hex-to-glsl](https://airtightinteractive.com/util/hex-to-glsl/) converter, or some other method
2. use a build-time macro:
```c
#define COLOR(hex) \
    { ((hex >> 24) & 0xFF) / 255.0f, ((hex >> 16) & 0xFF) / 255.0f, ((hex >> 8) & 0xFF) / 255.0f, (hex & 0xFF) / 255.0f }


static const float bordercolor[] = COLOR(0x282828ff);
static const float focuscolor[] = COLOR(0x3c3836ff);
static const float fullscreen_bg[] = COLOR(0x504945ff);
```

approach 2 seems alot easier.

**Comment by sevz17** [comment]
I'm fine with either option.
@djpohly what do you think?

**Comment by apprehensions** [comment]
another suggestion is to make a function to calculate it at run-time, similar to fnott, foot, etc:
```c
static const float bordercolor[] = 0x282828ff;
static const float focuscolor[] = 0x3c3836ff;
static const float fullscreen_bg[] = 0x504945ff;
```

**Comment by sevz17** [comment]
> another suggestion is to make a function to calculate it at run-time, similar to fnott, foot, etc:
> 
> ```c
> static const float bordercolor[] = 0x282828ff;
> static const float focuscolor[] = 0x3c3836ff;
> static const float fullscreen_bg[] = 0x504945ff;
> ```

Nah, it adds unnecessary lines.
