### ISSUE TITLE
[question] Wallpaper support.

### ISSUE THREAD

**Issue by FoundOne** [djpohly/dwl#48]
I know dwl is a tiling compositor and most of the times the apps will cover the background unless they are transparent, but I'd like to ask whether there will be a way to have a wallpaper in the future (probably with a third party program like wallutils) or it's a non-goal?

**Comment by djpohly** [comment]
I believe [swaybg](https://github.com/swaywm/swaybg) adds a background using the layer-shell protocol, and implementing layer-shell is definitely a goal for dwl.

**Comment by FoundOne** [comment]
I tried with swaybg and it just says:
``` 2020-08-24 04:32:43 - [swaybg-1.0/main.c:521] Missing a required Wayland interface ```
I guess that interface is missing. The setwallpaper command from wallutils fails too.

**Comment by djpohly** [comment]
Yes - a goal, but not implemented yet.

**Comment by SamHSmith** [comment]
@FoundOne lot's of things from bars to backgrounds to lockscreens use the layer shell. If we implement that we get the bunch.

**Comment by FoundOne** [comment]
Actually I already use the pull request for the layers. It a really great change.
