### ISSUE TITLE
A lot of build errors on main branch with wlroots 0.16.2 and git

### ISSUE THREAD

**Issue by Xgames123** [djpohly/dwl#482]
## Info
dwl version: 755fcae2afbed51f38c167bdc56a5437cda8137a
wlroots version: git and  0.16.2
## Description
The main branch fails to compile
I'm on archlinux

**Comment by Xgames123** [comment]
it turned out I had installed wlroots before without using pacman.
I removed that version and then it worked

**Comment by gplusplus314** [comment]
You saved me some aggravation. Thank you!
