### ISSUE TITLE
about the singletagset patch

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#483]
I added a new monitor recently and i have two monitors now:LVDS-1, VGA-1.

I modified waybar config file a little bit accordingly.

now dwl shows tags 1..9 on both monitors, so, i have two sets of tags, 18 in total.
 
I found that if i need to show tag7 on VGA-1, i have to select  monitor VGA-1 first and then MOD+7.

If i want show tag1..6 only on LVDS-1 and tag7..9 on VGA-1, simply hide some custom modules in waybar config file will do.

But, i still have to select VGA-1 first and MOD+7 to show tag7, i cannot just press MOD+7 when LVDS-1 is selected.

i downloaded the singletagset patch, it cannot be applied to current main branch. but I tried make changes to the "view" and "createmon" function as the singletagset patch, however dwl does not work as i expected after that.

i think that dwl should in someway knows that tag1..6 are for LVDS-1 and tag7..9 are on VGA-1, the information currently only in my waybar config file. but i don't understand how it was done in singletagset.

So, do i misunderstand the singletagset feature?

**Comment by bencollerson** [comment]
I added the singletagset patch. The point of the patch is all tags are shared between both (or more) monitors. So one set of tags from 1 to 9 can be viewed on any monitor, as opposed to having separate tag sets for each monitor. 

I really should make a new version of the patch from my current dwl fork. I just don't like debugging the toggletag and toggleview functions that I don't use because they confuse me. haha

**Comment by pm4rcin** [comment]
> I added the singletagset patch. The point of the patch is all tags are shared between both (or more) monitors. So one set of tags from 1 to 9 can be viewed on any monitor, as opposed to having separate tag sets for each monitor.
> 
> I really should make a new version of the patch from my current dwl fork. I just don't like debugging the toggletag and toggleview functions that I don't use because they confuse me. haha

From my understanding it's how sway handles tags by default right?

**Comment by bencollerson** [comment]
Probably. I based it on the dwm single tag set patch. 

https://dwm.suckless.org/patches/single_tagset/

**Comment by bencollerson** [comment]
Anyway does this patch work any better? https://github.com/djpohly/dwl/compare/main...bencollerson:dwl:singletagset

**Comment by sevz17** [comment]
Since this got attention, I'll close it and unsuscribe, please ping me if needed.

**Comment by guyuming76** [comment]
@bencollerson, thanks for explain that "The point of the patch is all tags are shared between both (or more) monitors. So one set of tags from 1 to 9 can be viewed on any monitor, as opposed to having separate tag sets for each monitor."

So, i did misunderstand what singletagset means.

Anyway, i have been working well for two weeks now with the DWL default approach for two monitors: same tag set 1-9 on both monitors. Just i need focus a specific monitor first if i want to select tag on that monitor. Its not so inconvenient and i can work with it.
