### ISSUE TITLE
IPC patch doesn't work with latest main branch

### ISSUE THREAD

**Issue by Xgames123** [djpohly/dwl#490]
## Info
dwl version: latest main
wlroots version: 0.16.2
## Description
I apply the ipc patch to the main branch using git.
Then I fix the patch error by doing this
```diff
        wl_resource_set_implementation(resource, &dwl_manager_implementation, NULL, dwl_manager_destroy);
 
        for (i = 0; i < tagcount; i++) {
-               zdwl_manager_v1_send_tag(resource, tags[i]);
+               zdwl_manager_v1_send_tag(resource, "1");
        }
```
Then waybar gives this error:
```
dwl_status_manager_v2 not advertised
```

**Comment by fauxmight** [comment]
If the trouble is not specific to your individual setup, this one is an issue for the maintainer of the IPC patch.

I don't personally use the IPC patch and cannot offer much that way, but I know it is broadly used and you may also chat on the Discord channel with those who are using it regularly to see whether or not the problem is universal.

**Comment by Xgames123** [comment]
Thanks for your response
I asked on the discord
How do I reach the ipc maintainer because the ipc patch is merged into the wiki

**Comment by fauxmight** [comment]
The author's repository can be found on the dwl wiki page for the IPC patch.

**Comment by sevz17** [comment]
> The author's repository can be found on the dwl wiki page for the IPC patch.

Although sometimes they disable issues for their repos...

**Comment by fbushstone** [comment]
I had to apply the patch manually. Unfortunately, I don't think you can just use `patch -i` and expect things to work.

**Comment by PalanixYT** [comment]
> Although sometimes they disable issues for their repos...
It's the default behaviour on Github

**Comment by sevz17** [comment]
> > Although sometimes they disable issues for their repos...
> 
> It's the default behaviour on Github

Really?, that's interesting... I guess the default behavior changed b/c I don't recall enabling them in my repo (or maybe I enabled them but don't remember).

Well, whatever. In any case you can comment on one of their commits they made.
