### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Zerogaku** [djpohly/dwl#492]
Hi I've been curious about moving to wayland and currently use dwm, I would like to know how I should go about migrating my setup (the dwm config) into dwl, am I supposed to patch from the ground up again? or can I replace dwl's files with my patched config (like dwm.c and config.h), and if there are any limitations to the patches or is dwl a 1 to 1 clone of dwm, I'm assuming status bars like dwmblocks are out of the question.

**Comment by PalanixYT** [comment]
dwl does not have a built in bar. You can look into the wiki for more information about bars and how to set them up. you can use statusgenerators like dwmblocks(look at the -p flag) with some bars. 

dwl is also not a port, but completely rewritten. while many interfaces look the same, patches are not compatible. You would have to repatch everything from the ground up. Feel free to ask around on the irc or discord.

**Comment by Zerogaku** [comment]
thanks, so most if not all the available patches of dwm would work with dwm? i'm a little curious about how it would handle the alpha patch, since dwl is the compositor, i'm assuming dwl would handle the transparency?

**Comment by fauxmight** [comment]
No. As @PalanixYT noted above, dwl is a complete rewrite and dwm patches definitely will **not** be directly usable in dwl.

If you take a look at the [wiki](https://github.com/djpohly/dwl/wiki), there are many patches already written for dwl including an 'alphafocus' patch that does some of what dwm's alpha patch does.

dwl does not include a bar and one typically chooses a third-party bar to use with dwl. [Waybar](https://github.com/Alexays/Waybar) (among others?) can have the dwl-alpha style transparency if you wish it to.

**Comment by Zerogaku** [comment]
thanks for clearing the confusion!
