### ISSUE TITLE
MPV freezes DWL

### ISSUE THREAD

**Issue by FoundOne** [djpohly/dwl#50]
How to reproduce:
Open a video with mpv and try to switch to other tag and try to go back.

What happens:
dwl becomes unresponsive for some time. It happens even if the video is paused. I can close the compositor though.

Platform:
Manjaro-arm unstable aarch64 Pinebook Pro (RK3399).

**Comment by guidocella** [comment]
Happens to me too.

**Comment by muevoid** [comment]
This seems ok for me it does not freeze dwl however resizing is very stuttery for mpv.

**Comment by guidocella** [comment]
This no longer happens with mpv's git master.

**Comment by Eluminae** [comment]
It happen to me on qutebrowser (qt5-webengine) when toggling on fullscreen videos

**Comment by Eluminae** [comment]
And it happens with mpv too :D with or without fullscreen
