### ISSUE TITLE
Dwl

### ISSUE THREAD

**Issue by the-arxyn** [djpohly/dwl#505]
Will this work without a desktop environment (just a doubt coz im'a newbie)

**Comment by fauxmight** [comment]
@zayn Welcome!
Yes, dwl works without a DE and is normally run without a DE. It is aimed at those preferring a leaner, cleaner, personally customized setup.

**Comment by sevz17** [comment]
@fauxmight you pinged someone unrelated lol

@the-arxyn, yeah as fauxmight said dwl is normally run without a DE
