### ISSUE TITLE
Confusion about the Floating Rules

### ISSUE THREAD

**Issue by debeetle** [djpohly/dwl#507]
After switching into wayland, I can hardly handle with the floating window rules. Tools like xprop under X11 helps me with the window class and instance in dwm. But there's almost nothing under wayland I got from google. Do I miss anything about the 'app id' and the 'title'?
Any help will be appreciated! Thanks!

**Comment by sevz17** [comment]
You can launch a nested dwl and run the apps inside it, the app-id and title are printed in the status output

Alternatively on yambar (I haven't check if there are other bars that do the same) you can configure it to show any info you want, so you could use it to see the app-id and the title w/o requiring a nested compositor

**Comment by debeetle** [comment]
Thanks! That helps me a lot

**Comment by Hiqqup** [comment]
Maybe i am not getting something right, but ive tried
 ```
~ dwl -s zathura
WL-1 title 
WL-1 appid 
WL-1 fullscreen 
WL-1 floating 
WL-1 selmon 0
WL-1 tags 0 1 0 0
WL-1 layout 
```
and dont seem to be getting any details about window classes.
Also ive tried doing it from the tty and piping the outputs into a logfile ``` dwl -s zathura > log``` but that also doesnt give me any more logs. Let me know if i can provide any further details.

**Comment by sevz17** [comment]
dwl prints the status output to the child process (or if there is none, to stdout).
What `dwl -s zathura > log` does is print the status output to the stdin of zathura, which I think zathura does not read and will eventually block dwl, the correct way to do it is `dwl -s 'cat > /path/to/file & ; zathura'`, this way what will happen is that `cat` will read the input and redirect it to the file in the background and then the rest of the command will be executed.
