### ISSUE TITLE
libwlroots.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by debeetle** [djpohly/dwl#521]
## Info
dwl version: 0.4
wlroots version: 0.17.0-1
## Description

Cannot open dwl, and it reports that "libwlroots.so.11: cannot open shared object file: No such file or directory"
When i try to recompile the project, it reports "wir/types/wlr_idle.h: No such file or directory"

**Comment by sevz17** [comment]
dwl 0.4 and the main branch are meant to use wlroots 0.16.x

For wlroots 0.17.x you need to use #520

**Comment by sevz17** [comment]
I'm delaying the merge to let author patches time to update their patches, let users test if there are regressions and more importantly... because I have not finished the ChangeLog (#501) :)
