### ISSUE TITLE
Could not build dwl on Fedora 39

### ISSUE THREAD

**Issue by rbnrayan** [djpohly/dwl#524]
I have installed all dependencies listed in the README.md, but when i run `make` this build error shows up:

```
c99  `pkg-config --cflags wlroots wayland-server xkbcommon libinput ` -I. -DWLR_USE_UNSTABLE -D_POSIX_C_SOURCE=200809L -DVERSION=\"`git describe --tags --dirty 2>/dev/null || echo 0.5`\"  -g -pedantic -Wall -Wextra -Wdeclaration-after-statement -Wno-unused-parameter -Wno-sign-compare -Wshadow -Wunused-macros -Werror=strict-prototypes -Werror=implicit -Werror=return-type -Werror=incompatible-pointer-types -O1 -c dwl.c
dwl.c:20:10: fatal error: wlr/types/wlr_cursor_shape_v1.h: No such file or directory
   20 | #include <wlr/types/wlr_cursor_shape_v1.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:66: dwl.o] Error 1
```

I tried to search for a library to get this file but i cannot find it.
Did I miss something?

Thanks for the help!

**Comment by PalanixYT** [comment]
dwl migrated to codeberg
https://github.com/djpohly/dwl/issues/509

here is the fix
https://codeberg.org/dwl/dwl/issues/529

**Comment by rbnrayan** [comment]
> dwl migrated to codeberg
> https://github.com/djpohly/dwl/issues/509
> 
> here is the fix
> https://codeberg.org/dwl/dwl/issues/529

It works with that, thanks!
