### ISSUE TITLE
Dwl fails at setup_tty on Alpine with freeze/endless loop

### ISSUE THREAD

**Issue by matu3ba** [djpohly/dwl#55]
I am not sure at all, how to debug Musl or Kernel. I installed musl-dev and musl-dbg without fixing the missing symbol problem.
Do you have any advice on that or any idea about the bug?

The error happens in function setup_tty in wlroots code backend/session/direct.c 
```
204		if (ioctl(fd, KDSKBMODE, K_OFF)) {
209		if (ioctl(fd, KDSETMODE, KD_GRAPHICS)) {
```
The logs are attached. [This](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11124) may be related.
[dwl_gdb_moreInfo.txt](https://github.com/djpohly/dwl/files/5205081/dwl_gdb_moreInfo.txt)
[dwl_gdb.txt](https://github.com/djpohly/dwl/files/5205082/dwl_gdb.txt)

This time I have all dependencies installed as the following packages (probably some not needed) and wlroot master from github:
```
kwayland-server kwayland-server-dev wayland-dev wayland-libs-server cmake
ffmpeg-libs ffmpeg-dev
mesa-dev
meson wayland wayland-protocols wayland-libs-egl gegl-dev gegl mesa-egl
libdrm libdrm-dev mesa-gbm libinput libinput-dev libinput-libs xf86-input-libinput libxkbcommon libxkbcommon-dev libxkbcommon-x11 libxkbcommon-static udev eudev-libs eudev-dev
pixman pixman-dev pixman-static xcb-util xcb-util-errors xcb-util-errrors-dev libxcb libxcb-dev
libx11-dev xcb-util-wm xcb-util-wm-dev xcb-util-image xcb-util-image-dev
```

**Comment by djpohly** [comment]
So the call to `ioctl` is hanging?  That sounds like a kernel bug.  Do you see anything interesting in `dmesg` when this happens?

**Comment by matu3ba** [comment]
@djpohly I cant even change the tty with alt+f1. Does this mean that it creates a Kernel panic?

**Comment by matu3ba** [comment]
@djpohly No. The latest message is at round 5.5 seconds with "eth0: link becomes ready". So shortly after booting Alpine.

**Comment by Sevz17** [comment]
@matu3ba , do you still have this problem or can I close this issue?

**Comment by matu3ba** [comment]
I did not try again. I think you can close this for now.
