### ISSUE TITLE
Questions regarding dwl

### ISSUE THREAD

**Issue by Joe23232** [djpohly/dwl#57]
Forgive me for my lack of understanding but I am a bit confused, is this supposed to be a compositor or a WM? I thought `dwm` is a WM and `dwl` is supposed to mimic `dwm` but for `wayland`, so how come `dwl` refers itself to be a _compact, hackable compositor for Wayland based on wlroots._?

**Comment by guidocella** [comment]
Wayland doesn't have standalone window managers, its compositors are equivalent to X's display server + window manager + compositor.

**Comment by Joe23232** [comment]
Oh, so `dwl` treats it like a WM?

**Comment by guidocella** [comment]
It is mostly concerned with managing windows while using wlroots modules for lower level stuff.

**Comment by Joe23232** [comment]
I see, so `wlroots` is the low level implementation of managing windows and `dwl` is a wrapper for `wlroots` to manage it on a higher level?

**Comment by guidocella** [comment]
Yes but they also manage everything X used to do other than managing windows such as handling keyboard input and layouts, mouse input and cursors, plugging monitors, configuring them (modes, scales, transforms), user idle monitoring, power management, gamma control. Some of these are provided trivially by wlroots (https://github.com/djpohly/dwl/commit/1c9a0d88222e2f0b1049aec82ba7f5fab2a3dad9), others require us to write more code (like runtime output configuration which I'm attempting to implement).

**Comment by Joe23232** [comment]
I see, thank you :)

Just one last question, do you know any alternative to `dwl` which is configurable in Rust?

**Comment by guidocella** [comment]
I don't think there is any. You can check the Arch wiki for a list of compositors: https://wiki.archlinux.org/index.php/Wayland#Compositors

**Comment by Joe23232** [comment]
Thank you mate

**Comment by djpohly** [comment]
Or you could write a Rust program which outputs a `config.h` file and calls `make`. :wink:
