### ISSUE TITLE
The filepicker in firefox, vimb or libreoffice does not show

### ISSUE THREAD

**Issue by FoundOne** [djpohly/dwl#58]
It acts like there is a dialogue above (the app freezes until I hit Esc), but nothing gets displayed above or as additional window. I can't upload any files using firefox or vimb in dwl. That does not happen in plasma-wayland. The file picker in gimp and that in qtox, work fine though.

**Comment by guidocella** [comment]
Even though the popup isn't shown, if Esc works that means it accepts keyboard input, so until popup support is added, you can copy the file path to upload beforehand and press ctrl+l ctrl+v Enter as a workaround.

**Comment by ma-choo** [comment]
Did this get fixed? The file picker dialog in Firefox is working fine for me.

**Comment by Sevz17** [comment]
Hey @FoundOne, I'll close this issue, if it persist feel free to open again
