### ISSUE TITLE
Implementing support for external status bars

### ISSUE THREAD

**Issue by jackerschott** [djpohly/dwl#59]
First of all: Really cool project you started here. This will probably be all i need to switch to wayland.

I would really like to contribute, if i find the timei, and i would like to start working on support for external status bars.
So the question is, do you already have started something in this regard and what are your plans for the exact implementation?
Also, i don't know if this is the right place to ask this question, so feel free to point me to something else.

**Comment by guidocella** [comment]
#49 already allows using external bars such as waybar, though the maintainer hasn't been around to merge it. waybar won't show you tags and windows though since there's no support for dwl, but they may be open to merging it in the future since they added it for river (Alexays/Waybar#745).

**Comment by jackerschott** [comment]
Ok, seems like i missed that. So with this dwl can recognize external status bar windows, handle them correctly and also tell the status bar which tags are active and used by windows, so it can display this, right? If so, out of curiosity, how do you did you handle the interprocess communication between dwl and external status bars? I mean this would be a new feature not present in the original dwm project, as for as i know.

**Comment by guidocella** [comment]
They don't recognize which tags are active, that has to be implemented. As of now only compositor-indipendent waybar modules like backlight and battery work.

**Comment by djpohly** [comment]
Is there further work needed on this now that #49 is merged?

**Comment by djpohly** [comment]
Fixed by #91.
