### ISSUE TITLE
Is anyone working on layer shell?

### ISSUE THREAD

**Issue by SamHSmith** [djpohly/dwl#60]
From my understanding wlroots already has a lot of the support for layer shell built in. And that we simply need to enable/use it. This should be high priority since enabing layer shell support will give us support for 75% of ecosystem features. Backgrounds, lockscreens, widgets, bars, indicators, notifications will all work if we can just get this implemented.

**Comment by djpohly** [comment]
See the work in PR #49.  Everything in Wayland sounds simple until you actually try to do it (take a look at the diffstat).

**Comment by guidocella** [comment]
Lockscreens actually require implementing wlr-input-inhibitor-unstable-v1 as well. Also, my pull request isn't even a full implementation of layer shell since popups (used at least by waybar) would require maybe 300 more lines.

**Comment by SamHSmith** [comment]
I know this is suckless and all but shouldn't we support the full protocol?

**Comment by guidocella** [comment]
In my opinion we should think about popups after the core layer shell implementation is merged. I personally don't care about them so I would rather implement other protocols next.

**Comment by FoundOne** [comment]
I still can't upload files in Firefox-wayland. I guess it uses popups for the file selector. I'm not sure tho If it's not I'll delete this and make a new report. I still can't find a work around about this.

**Comment by guidocella** [comment]
I think so since https://wayland-book.com/xdg-shell-in-depth/popups.html mentions "following a path like "File → Recent Documents → Example.odt". I didn't realize they were used for that too, I guess we will have to be add them to mainline dwl eventually.

**Comment by guidocella** [comment]
Firefox's file picker works in the newest version. The bug was https://bugzilla.mozilla.org/show_bug.cgi?id=1639575, it doesn't use popups.
