### ISSUE TITLE
Avoid overlaping of tiled and floating windows (like dwm)

### ISSUE THREAD

**Issue by notthewave** [djpohly/dwl#75]
![Screenshot from 2021-01-04 10-42-05](https://user-images.githubusercontent.com/74874782/103521564-46c11380-4e79-11eb-8085-abdab45d952c.png)

I'm guessing this is now doable as layershell is implemented.

**Comment by djpohly** [comment]
I can think of two options for implementing this (and I don't think it'll require layer-shell).  One, we add yet another pass to the rendering code (which is already quite long thanks to layer-shell and XWayland).  Two, we manage the `stack` list in such a way that the floating windows remain on top.  I'm not sure which would end up being the simpler approach - try both and compare?
