### ISSUE TITLE
XWayland compilation errors

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [djpohly/dwl#78]
Compiling dwl with XWayland support results in lots of compilation errors. I haven't taken the time to look through all of these, but from what I've seen it looks like certain types, variables, and functions are undeclared.

I haven't taken a look through all the files yet but I'll get around to it.

Here is the log: [error.log](https://github.com/djpohly/dwl/files/5789714/error.log)

I'm curious to know whether dwl relies on some up-to-date version of wlroots, because earlier today I got compilation errors in the main code that I resolved by installing wlroots-git from the AUR.
I'm on Artix if that helps.

**Comment by djpohly** [comment]
I'm on Artix as well and can't reproduce the issue.  Have you modified the source or config.h at all?

**Comment by InfiniteWorldSoftware** [comment]
I've modified the source of config.def.h.

**Comment by djpohly** [comment]
Is that where you tried to enable XWayland?  Build parameters are in config.mk.

**Comment by InfiniteWorldSoftware** [comment]
Yes, I did `#define XWAYLAND`.
I haven't taken a look at config.mk.

**Comment by djpohly** [comment]
(Also, yes, we track with wlroots-git.  It's in the README, I'm pretty sure. :slightly_smiling_face:)

**Comment by InfiniteWorldSoftware** [comment]
Let me try that in config.mk.

**Comment by InfiniteWorldSoftware** [comment]
Okay, I got it to build. I'll get back to you and see if X apps work on my machine.
Thanks!

**Comment by InfiniteWorldSoftware** [comment]
It doesn't launch, but I'm on nvidia and that's expected. I can probably get it to work with nouveau at some point.
