### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by CarDGee** [djpohly/dwl#82]
Hello its not building on master branch with following error
"dwl.c:2018:18: error: too few arguments to function ‘wlr_backend_autocreate’
 2018 |  if (!(backend = wlr_backend_autocreate(dpy)))"

**Comment by meutraa** [comment]
Master is tracking wlroots master. wlroots 0.12.0 will not work.

**Comment by djpohly** [comment]
Correct - this was a recent change in wlroots.  Update to latest wlroots-git and everything should be good!
