### ISSUE TITLE
Is the version of wlroots required for dwl too old?

### ISSUE THREAD

**Issue by xerxeslins** [djpohly/dwl#90]
I am using wlroots 0.12.0

$ make

cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/elogind        -c -o dwl.o dwl.c
dwl.c: In function ‘keypress’:
dwl.c:1287:19: error: comparison between ‘enum wlr_key_state’ and ‘enum wl_keyboard_key_state’ [-Werror=enum-compare]
 1287 |  if (event->state == WL_KEYBOARD_KEY_STATE_PRESSED)
      |                   ^~
dwl.c: In function ‘setup’:
dwl.c:1998:18: error: too few arguments to function ‘wlr_backend_autocreate’
 1998 |  if (!(backend = wlr_backend_autocreate(dpy)))
      |                  ^~~~~~~~~~~~~~~~~~~~~~
In file included from dwl.c:15:
/usr/include/wlr/backend.h:43:21: note: declared here
   43 | struct wlr_backend *wlr_backend_autocreate(struct wl_display *display,
      |                     ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: dwl.o] Error 1

**Comment by djpohly** [comment]
Please read the README - wlroots-git is required.
