### ISSUE TITLE
Too difficult to switch from Xorg's dwm

### ISSUE THREAD

**Issue by kaihendry** [djpohly/dwl#92]
https://github.com/djpohly/dwl/blob/main/config.def.h is jarring, since it doesn't allow an easy switch from https://git.suckless.org/dwm/file/config.def.h.html

* natural scrolling on by default
* no status bar AFAICT, even though it's mentioned as [in-built in the README](https://github.com/djpohly/dwl/blob/main/README.md) and that why the code is larger
* no dmenu

**Comment by Fuseteam** [comment]
isn't no dmenu related to dmenu being an X app?

**Comment by kaihendry** [comment]
Is there no Wayland equivalent that can be bound in the same way?

**Comment by Fuseteam** [comment]
if dmenu doesn't run, i don't know of a wayland equivalent no

**Comment by Stivvo** [comment]
[bemenu](https://github.com/Cloudef/bemenu) is a good replacement  for dmenu, while natural scrolling can be easily be disabled  [here](https://github.com/djpohly/dwl/blob/9f90011ea28a4b0fde87c4478a793f9da8b71ea6/config.def.h#L52), I agree that it shouldn't be on by default though.

**Comment by kaihendry** [comment]
Is there some example of bemenu app launcher in dwl? https://github.com/search?q=bemenu+filename%3Aconfig.h&ref=simplesearch

**Comment by ahmadraniri1994** [comment]
I need to know how to assign keybind, at least for command/app launcher. Any advice? Dwl doesn't come with manual either. *Sigh*.

**Comment by Fuseteam** [comment]
@ahmadraniri1994 that's the same way it is done in dwm fwiw

**Comment by ahmadraniri1994** [comment]
> that's the same way it is done in dwm fwiw

yep... surprisingly I never configurre dwm before, but I can do it on dwl, which is nice.

**Comment by djpohly** [comment]
Good points here - it is a goal to make the transition as easy as possible.

* Status bar - I can see that the README needs to be worded more clearly.  The mention of a "built-in status bar" was meant as the exception to the feature parity goal.  As soon as there is a dzen for Wayland, please someone let me know!
* Launcher - good point, there is a default in dwm's config.h, so there should be one here as well
* Natural scrolling - hmm... yeah, I think you're right here as well. Normally this would be configured in Xorg.conf, which is subsumed by the compositor in Wayland, so the option should be present, but the Xorg default should be the dwl default.

**Comment by kaihendry** [comment]
I still don't understand the sentiment with the status bar. I expect something like:

<img src="https://s.natalian.org/2021-03-14/dwm.png">

When I launch dwl, rn nothing exists.

**Comment by ahmadraniri1994** [comment]
@kaihendry, yeah, the simple one is more than enough.

**Comment by michaelskyba** [comment]
What's the intended solution for getting it? Swaybar and stuff like that are complete overkill - something like xsetroot would be ideal
