### ISSUE TITLE
Crashes when trying to fullscreen nonexistent window

### ISSUE THREAD

**Issue by AJ-Williams1** [djpohly/dwl#93]
# Behavior
When you press the keybind to fullscreen a window, but there is no window in focus (i.e. the workspace is empty), dwl crashes.

# Expected behavior
It should just ignore the keybind if there is no window.

**Comment by Stivvo** [comment]
This has already been fixed in #69. The merge conflicts are due to the recent split of dwl in two branches.

**Comment by djpohly** [comment]
Fixed by #69.
