### ISSUE TITLE
cannot start programs with Xwayland

### ISSUE THREAD

**Issue by NPScript** [djpohly/dwl#97]
I'm trying to switch from dwm to dwl but I can't get Xwayland working:
I uncommented `CFLAGS+=-DXWAYLAND` but I can't start any X Client

If I try to start a X Client it throws the error `Failed to activate virtual core keyboard: 2`

What did I forget?

**Comment by ntrp** [comment]
I am having a similar issue.. XWayland programs just hang with no output

**Comment by NPScript** [comment]
As much as I understand the function `xwaylandready` should be called when a new Xwayland program launches but it is never called, do you know why?

**Comment by djpohly** [comment]
The problem is that the Xwayland implementation in wlroots won't let us have our own signal handling - in particular, ignoring `SIGCHLD` to avoid having to deal with zombies makes the Xwayland server startup code hang.
