### ISSUE TITLE
Print "layout / mode" status or workspace we're on.

### ISSUE THREAD

**Issue by ahmadraniri1994** [djpohly/dwl#99]
Is there a method / way to know "recent using mode" (float, monocle, tiled) and workspace we're on, like "Oh, I am on workspace 1 right now.".

**Comment by Stivvo** [comment]
Maybe you need a status bar #59 #91

**Comment by ahmadraniri1994** [comment]
@Stivvo yeah, I am using waybar rn, it's good.

**Comment by djpohly** [comment]
This was merged in #91. :)

**Comment by ahmadraniri1994** [comment]
![20210331_08h11m29s_grim](https://user-images.githubusercontent.com/72283174/113076712-dae11380-91f9-11eb-9d31-a13ba21fc78a.png)
Now I can show the layouts, thanks, I just need to figure out about showing workspaces.
